/**
 * Loan program pages.
 *
 * Every page here is educational. None of it states a rate, a fee, a limit that
 * changes annually, an approval threshold, or a claim that a specific borrower
 * qualifies — those require a current primary source and a licensed human, and
 * they belong in a conversation, not a static page.
 *
 * `sources` are the primary references a reviewer must check before this page
 * moves from noindex to index. `requiresLenderPath` marks programs the company
 * cannot offer until an executed broker agreement covers them.
 */

export type ProgramSource = { publisher: string; title: string; url: string };

/**
 * Optional hero photography.
 *
 * Optional on purpose: a program with no image that genuinely fits renders
 * exactly as it did before rather than borrowing a picture that misdescribes it.
 *
 * Every one of these is generic Florida scenario photography, generated by us.
 * None of it is a client, a TRACT office, a member of staff, or a particular
 * property, and the alt text is written so it cannot be read as any of those.
 * It illustrates the situation the page is about; it does not evidence anything.
 */
export type ProgramHeroImage = {
  src: string;
  alt: string;
  /** Intrinsic dimensions. Present so the hero does not reflow when it loads. */
  width: number;
  height: number;
};

const SCENARIO_IMAGES = {
  purchase: {
    src: "/images/scenarios/purchase.webp",
    alt: "A pale blue Florida cottage with a metal roof, a front porch and a white picket fence",
    width: 900,
    height: 502
  },
  refinance: {
    src: "/images/scenarios/refinance.webp",
    alt: "An established Florida ranch house with a tile roof beneath live oaks draped in Spanish moss",
    width: 900,
    height: 502
  },
  investment: {
    src: "/images/scenarios/investment.webp",
    alt: "A two-storey Florida stucco house with two separate front doors and a shared driveway",
    width: 900,
    height: 502
  },
  selfEmployed: {
    src: "/images/scenarios/self-employed.webp",
    alt: "A work van on the driveway of a Florida home beside an open garage fitted out as a workshop",
    width: 900,
    height: 502
  },
  construction: {
    src: "/images/scenarios/construction.webp",
    alt: "The timber frame of a new Florida house standing on a cleared sandy lot",
    width: 900,
    height: 502
  },
  condo: {
    src: "/images/scenarios/condo.webp",
    alt: "A beachfront Florida condominium building with tiered balconies and palms against the ocean",
    width: 900,
    height: 502
  }
} as const satisfies Record<string, ProgramHeroImage>;

export type Program = {
  slug: string;
  navLabel: string;
  h1: string;
  title: string;
  description: string;
  eyebrow: string;
  summary: string;
  mayFit: string[];
  exploreAlternativesIf: string[];
  howItWorks: { heading: string; body: string }[];
  variables: { label: string; body: string }[];
  faqs: { question: string; answer: string }[];
  relatedCalculators: { href: string; label: string }[];
  relatedPrograms: string[];
  sources: ProgramSource[];
  requiresLenderPath: boolean;
  loanTypeForSchema: string | null;
  /** Illustrative only. Absent where no scenario image honestly fits the page. */
  heroImage?: ProgramHeroImage;
};

const CFPB_MORTGAGE: ProgramSource = {
  publisher: "Consumer Financial Protection Bureau",
  title: "Mortgages — buying a house",
  url: "https://www.consumerfinance.gov/consumer-tools/mortgages/"
};

export const PROGRAMS: Program[] = [
  {
    slug: "purchase",
    heroImage: SCENARIO_IMAGES.purchase,
    navLabel: "Buying a home",
    h1: "Financing a home purchase in Florida",
    title: "Home Purchase Financing in Florida",
    description:
      "What actually determines your payment, your cash to close, and your options when buying a home in Florida.",
    eyebrow: "Purchase",
    summary:
      "A purchase mortgage is the loan you use to buy a home. The interesting part is not the loan itself — it is the interaction between price, down payment, rate, term, taxes, and insurance, because in Florida the last two move the payment more than most buyers expect.",
    mayFit: [
      "You are buying a primary residence, second home, or investment property",
      "You want to understand your realistic payment range before you write offers",
      "You need to know how much cash you actually need at closing, not just the down payment"
    ],
    exploreAlternativesIf: [
      "You already own the home and want to change your rate or term — that is a refinance",
      "You are buying with cash and only want a comparison of the tradeoffs"
    ],
    howItWorks: [
      {
        heading: "You establish a realistic budget",
        body: "Start with the full monthly cost, not the principal and interest alone. In Florida, property taxes, homeowners insurance, wind coverage, flood coverage where applicable, and HOA dues frequently add more to the payment than buyers plan for. The payment calculator lets you enter each one separately so you can see which line is driving the number."
      },
      {
        heading: "You get a conversation, then a documented review",
        body: "A licensed loan originator reviews your income, obligations, credit profile, assets, and timeline. That conversation is what turns a calculator estimate into an actual set of options, and it is the point at which real program eligibility can be assessed."
      },
      {
        heading: "You apply through a secure system",
        body: "The application itself happens in the approved secure system, not on a marketing form. That is where documents belong, and it is where the required disclosures are issued and tracked."
      },
      {
        heading: "The lender underwrites and you close",
        body: "The lender verifies what was represented, orders an appraisal, and issues conditions. Timelines depend on the lender, the property, and how quickly documentation is returned."
      }
    ],
    variables: [
      {
        label: "Down payment",
        body: "Changes the loan amount, whether mortgage insurance applies, and often the pricing. It is not the same as cash to close."
      },
      {
        label: "Credit profile",
        body: "Affects which programs are available and how a loan is priced. Different programs weigh it differently."
      },
      {
        label: "Debt-to-income ratio",
        body: "Your existing monthly obligations reduce the housing payment a lender will support. Paying off a small balance sometimes matters more than a larger down payment."
      },
      {
        label: "Property type and occupancy",
        body: "A condo, a manufactured home, a second home, and an investment property are each underwritten differently. Florida condo financing in particular has its own project-level review."
      },
      {
        label: "Insurance",
        body: "Florida homeowners and wind premiums vary enormously by county, construction, roof age, and carrier. Get a real quote early; an assumed premium can move your qualifying payment materially."
      }
    ],
    faqs: [
      {
        question: "How much do I need for a down payment?",
        answer:
          "It depends entirely on the loan program, the property, and your profile. Several programs allow far less than twenty percent. The more useful question is how much total cash you need at closing, which includes closing costs and prepaid items — the closing cost calculator breaks that down."
      },
      {
        question: "Does using a broker cost more than going to a bank?",
        answer:
          "Not inherently. A broker works with multiple lenders, which means comparing options rather than being limited to one institution's products. What a specific transaction costs depends on the lender and the loan; we will show you the actual figures before you commit to anything."
      },
      {
        question: "Can you tell me my rate today?",
        answer:
          "Not from a web page. Rates move daily and price differently depending on credit, loan-to-value, property type, occupancy, loan amount, and lock period. Anyone publishing a single rate without those inputs is showing you an advertisement, not your rate."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/mortgage-payment", label: "Estimate a monthly payment" },
      { href: "/calculators/affordability", label: "Explore an affordability range" },
      { href: "/calculators/closing-cost", label: "Plan your cash to close" }
    ],
    relatedPrograms: ["first-time-home-buyers", "conventional", "fha"],
    sources: [CFPB_MORTGAGE],
    requiresLenderPath: true,
    loanTypeForSchema: "Purchase money mortgage"
  },
  {
    slug: "refinance",
    heroImage: SCENARIO_IMAGES.refinance,
    navLabel: "Refinancing",
    h1: "Refinancing a mortgage in Florida",
    title: "Mortgage Refinancing in Florida",
    description:
      "When a refinance is worth the cost, how break-even actually works, and the tradeoff a lower payment can hide.",
    eyebrow: "Refinance",
    summary:
      "A refinance replaces your existing mortgage with a new one. It can lower a rate, change a term, remove mortgage insurance, or convert equity to cash. It always has a cost, so the question is never just whether the new rate is lower — it is whether you hold the loan long enough for the savings to exceed what you paid to get them.",
    mayFit: [
      "Your current rate is meaningfully above what is available to you now",
      "You want to shorten your term and can support the higher payment",
      "You have equity and a specific, considered use for it"
    ],
    exploreAlternativesIf: [
      "You expect to sell or move before you reach break-even",
      "You are close to paying off the loan and would be restarting amortization",
      "The only goal is a lower payment and a longer term would cost you more in total interest than you realize"
    ],
    howItWorks: [
      {
        heading: "You establish the real cost",
        body: "Refinance costs include lender fees, title, recording, and prepaid items. Financing those costs into the balance does not make them free — it moves them into the loan where you pay interest on them."
      },
      {
        heading: "You calculate break-even honestly",
        body: "Divide the cost by the monthly payment reduction. That is the number of months before the refinance has paid for itself. If you will not be in the loan that long, the math does not work regardless of how good the rate looks."
      },
      {
        heading: "You compare total interest, not just payment",
        body: "Extending from a fifteen-year remaining term back to thirty years lowers the payment and can substantially increase total interest. Our calculator shows both figures side by side for exactly this reason."
      }
    ],
    variables: [
      {
        label: "Remaining term",
        body: "How far into your current loan you are changes the comparison completely."
      },
      { label: "Closing costs", body: "The single largest driver of break-even." },
      {
        label: "How long you will stay",
        body: "The assumption that determines whether break-even is reachable."
      },
      {
        label: "Mortgage insurance",
        body: "Removing it can change the math even when the rate improvement is modest."
      },
      { label: "Cash-out amount", body: "Increases the balance and usually affects pricing." }
    ],
    faqs: [
      {
        question: "Is there a rule of thumb, like one percent?",
        answer:
          "No. A rule of thumb ignores your balance, your remaining term, your costs, and how long you will stay. On a large balance a quarter point can be worth it; on a small balance a full point may not be. Run your own numbers."
      },
      {
        question: "Can I skip a payment when I refinance?",
        answer:
          "You are not skipping anything. What appears to be a skipped payment is interest handled through payoff and prepaid items. Framing it as free is a marketing tactic, not a benefit."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/refinance-break-even", label: "Calculate your break-even point" },
      { href: "/calculators/mortgage-payment", label: "Compare payments" }
    ],
    relatedPrograms: ["conventional", "va"],
    sources: [CFPB_MORTGAGE],
    requiresLenderPath: true,
    loanTypeForSchema: "Refinance mortgage"
  },
  {
    slug: "first-time-home-buyers",
    heroImage: SCENARIO_IMAGES.purchase,
    navLabel: "First-time buyers",
    h1: "First-time home buyers in Florida",
    title: "First-Time Home Buyer Guide for Florida",
    description:
      "The sequence that actually matters when you have never done this before, and where first-time buyers most often get surprised.",
    eyebrow: "First-time buyers",
    summary:
      "Being a first-time buyer is not a loan program. It is a status that can make you eligible for certain assistance programs and that changes what you need explained. The financing itself is the same set of options everyone else has.",
    mayFit: [
      "You have not owned a home in the past three years",
      "You want the process explained in order, without jargon",
      "You want to know what assistance programs exist before assuming you do not qualify"
    ],
    exploreAlternativesIf: [
      "You have owned recently and are moving up — the mechanics change when you have a home to sell"
    ],
    howItWorks: [
      {
        heading: "Understand the full cost of ownership",
        body: "Payment, taxes, insurance, maintenance, and utilities. The mortgage payment is the part that gets quoted; the rest is what determines whether the home is comfortable to own."
      },
      {
        heading: "Look at assistance programs before ruling them out",
        body: "Florida Housing administers homebuyer programs with their own eligibility rules, income limits, and purchase price limits, and those change. We check the current program terms directly rather than working from memory."
      },
      {
        heading: "Get your financing conversation done before you shop",
        body: "Knowing your realistic range before you tour homes saves you from falling in love with a house you cannot comfortably carry."
      }
    ],
    variables: [
      {
        label: "Assistance program eligibility",
        body: "Income limits, purchase price limits, and occupancy requirements vary and change."
      },
      {
        label: "Down payment source",
        body: "Gift funds, savings, and assistance funds are each documented differently."
      },
      {
        label: "Credit history depth",
        body: "A thin file is not the same problem as a damaged one and is often solvable."
      }
    ],
    faqs: [
      {
        question: "Do I need twenty percent down?",
        answer:
          "No. That figure persists because it is the point at which conventional mortgage insurance is typically not required. Several programs allow substantially less."
      },
      {
        question: "What credit score do I need?",
        answer:
          "There is no single number, because requirements differ by program and lenders apply their own overlays on top. A conversation about your actual profile is more useful than a threshold from a web page."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/affordability", label: "See an affordability range" },
      { href: "/calculators/closing-cost", label: "Plan your cash to close" }
    ],
    relatedPrograms: ["fha", "conventional", "purchase"],
    sources: [
      CFPB_MORTGAGE,
      {
        publisher: "Florida Housing Finance Corporation",
        title: "Homebuyer programs overview",
        url: "https://www.floridahousing.org/programs/homebuyer-overview-page"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "conventional",
    heroImage: SCENARIO_IMAGES.purchase,
    navLabel: "Conventional",
    h1: "Conventional mortgages",
    title: "Conventional Mortgages in Florida",
    description:
      "How conventional financing works, when mortgage insurance applies, and where it differs from government-backed options.",
    eyebrow: "Program",
    summary:
      "A conventional mortgage is not insured or guaranteed by a government agency. Most conventional loans are written to standards set by Fannie Mae or Freddie Mac, which is why their requirements are relatively consistent across lenders — though every lender may add its own overlays.",
    mayFit: [
      "You have a reasonably established credit profile",
      "You want the option to remove mortgage insurance once you reach sufficient equity",
      "You are buying a second home or investment property, where government programs generally do not apply"
    ],
    exploreAlternativesIf: [
      "Your credit profile or down payment would be better served by a government-backed program",
      "You are eligible for VA financing, which has meaningfully different economics"
    ],
    howItWorks: [
      {
        heading: "Agency standards set the baseline",
        body: "Eligibility, documentation, appraisal, and property requirements follow the current agency selling guides. Those guides are updated regularly, so current terms are verified at the time of your application rather than quoted from memory."
      },
      {
        heading: "Mortgage insurance is tied to equity",
        body: "Conventional mortgage insurance generally applies below a threshold of equity and can typically be removed once sufficient equity is established. The specific rules and timing are program- and servicer-dependent."
      }
    ],
    variables: [
      { label: "Loan-to-value ratio", body: "Drives both mortgage insurance and pricing." },
      {
        label: "Credit profile",
        body: "Conventional pricing is more sensitive to credit than some government programs."
      },
      {
        label: "Occupancy",
        body: "Primary, second home, and investment are priced and underwritten differently."
      },
      {
        label: "Loan limit",
        body: "Conforming limits are set annually. Above them, the loan is a jumbo and follows different rules."
      }
    ],
    faqs: [
      {
        question: "Can conventional mortgage insurance be removed?",
        answer:
          "Generally yes, once sufficient equity is established, subject to the applicable rules and your servicer's requirements. This is a meaningful difference from some government programs and worth discussing before you choose a path."
      },
      {
        question: "What is the conforming loan limit?",
        answer:
          "It is set annually and varies by county. We check the current published limit for your specific county rather than working from a figure that may be out of date."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["jumbo", "fha", "purchase"],
    sources: [
      {
        publisher: "Fannie Mae",
        title: "Selling Guide",
        url: "https://selling-guide.fanniemae.com/"
      },
      {
        publisher: "Freddie Mac",
        title: "Seller/Servicer Guide",
        url: "https://guide.freddiemac.com/"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: "Conventional mortgage"
  },
  {
    // One page for both second-lien instruments, because the real decision is
    // between them (and against a cash-out refinance), not within either one.
    // Covers two products, so no single loanType is honest for the schema.
    slug: "home-equity",
    heroImage: SCENARIO_IMAGES.refinance,
    navLabel: "Home equity",
    h1: "Home equity lines and second mortgages in Florida",
    title: "HELOCs and Second Mortgages in Florida",
    description:
      "How a home equity line of credit differs from a closed-end second mortgage, and when a cash-out refinance beats both.",
    eyebrow: "Home equity",
    summary:
      "A home equity line of credit and a closed-end second mortgage both borrow against the equity in a home you already own, without touching your existing first mortgage. Which one fits — or whether replacing the whole loan with a cash-out refinance beats both — turns mostly on the rate you already have and on how you actually plan to use the money.",
    mayFit: [
      "You have meaningful equity and a first mortgage whose terms you want to keep",
      "You want flexible access to funds over time — a renovation done in stages, for example — rather than one lump sum, which is what a line of credit is built for",
      "You need a single fixed amount with a predictable payment, which is what a closed-end second mortgage provides",
      "You want the draw period, the repayment period, and the variable-rate mechanics explained before you talk to any lender"
    ],
    exploreAlternativesIf: [
      "Your existing first-mortgage rate is high enough that replacing the entire loan could make sense — that is a cash-out refinance, and it deserves a direct comparison before you add a second lien",
      "You would be borrowing to cover recurring living expenses — putting your home behind an ongoing shortfall tends to compound the problem rather than solve it",
      "The amount is small and short-lived enough that closing costs and a lien on your home outweigh the convenience of the credit",
      "A payment that can rise would strain your budget — most lines of credit carry a variable rate, and the minimum payment typically steps up when the draw period ends"
    ],
    howItWorks: [
      {
        heading: "Your equity sets the ceiling",
        body: "Lenders size both instruments against combined loan-to-value: your first-mortgage balance plus the new line or loan, divided by the home's appraised value. Each lender sets its own maximum, and it moves with credit profile, occupancy, and property type. The practical consequence is that two lenders can offer meaningfully different amounts against the identical house, which makes comparing more than one worth the effort."
      },
      {
        heading: "A line of credit runs in two phases",
        body: "During the draw period you can borrow, repay, and borrow again up to the limit, and interest accrues only on what you have actually drawn — minimum payments during this phase are often interest-only. When the draw period ends, the repayment period begins: no new draws, and the payment is recalculated to retire the principal. Because most lines carry a variable rate built from an index plus a margin, the payment can change over the life of the line, and the jump at the end of the draw period surprises people who only budgeted for the interest-only minimum."
      },
      {
        heading: "A closed-end second mortgage is the fixed alternative",
        body: "A closed-end second — often called a home equity loan — delivers one lump sum at closing and amortizes it on a set schedule, typically at a fixed rate. There is no draw flexibility and no reuse of repaid principal; in exchange you get a payment that does not move. If the plan is a single defined expense rather than staged spending, this structure is frequently the better match."
      },
      {
        heading: "Your first mortgage stays exactly as it is",
        body: "Neither instrument replaces or reprices your existing first mortgage — that is the entire appeal when the loan you already have is worth keeping. Both, however, place a lien on your home behind the first. The home secures the debt, which means failing to repay can ultimately mean losing the house. That is the sentence to sit with before treating home equity as convenient money."
      }
    ],
    variables: [
      {
        label: "Combined loan-to-value",
        body: "The first-mortgage balance plus the new lien, measured against appraised value. It gates how much any lender will extend, and each lender caps it differently."
      },
      {
        label: "Credit profile",
        body: "Drives availability and, on a line of credit, the margin added to the index — which follows the balance for the life of the line."
      },
      {
        label: "Your existing first-mortgage rate",
        body: "The pivot of the whole decision. A first mortgage worth keeping argues for a second lien; one you would happily replace argues for pricing a cash-out refinance instead."
      },
      {
        label: "How you will actually draw",
        body: "A line drawn fully on day one behaves like a lump-sum loan at a variable rate — the flexibility you paid for goes unused. Staged spending is where a line earns its keep."
      },
      {
        label: "Rate structure",
        body: "Which index, what margin, how often the rate adjusts, and the lifetime cap all vary by lender. Some let you fix the rate on a portion of the balance; whether and how depends on the program."
      }
    ],
    faqs: [
      {
        question: "Should I get a HELOC or do a cash-out refinance?",
        answer:
          "Run both, honestly. A cash-out refinance replaces your entire first mortgage, so its cost includes whatever happens to the rate on money you already owe; a second lien leaves the first mortgage alone but adds its own rate and costs on the new money. Which wins depends on your current rate, the amount, and how long you will carry it — our refinance guide and break-even calculator exist for exactly this comparison."
      },
      {
        question: "What happens when the draw period ends?",
        answer:
          "New borrowing stops and the payment is recalculated to repay the principal over the repayment period. If you were paying interest-only minimums, that step-up can be substantial, and some lines are structured with a balloon instead of full amortization. Ask any lender to show you the repayment-phase payment on a fully drawn line before you open it — it is the number the marketing rarely leads with."
      },
      {
        question: "Is the interest tax-deductible?",
        answer:
          "It depends on how the money is used and on current tax law, both of which are outside what a mortgage brokerage should be advising you on. Talk to a tax professional about your specific situation before you count on a deduction."
      },
      {
        question: "Can the lender freeze or reduce my line?",
        answer:
          "Yes, in defined circumstances — federal rules permit a lender to suspend draws or reduce a limit when, for example, the property's value declines significantly or a borrower's financial circumstances change materially. A line you are keeping as an emergency reserve can therefore shrink at precisely the moment broader conditions worsen, which is worth weighing if the reserve is the whole plan."
      },
      {
        question: "What does it cost to open?",
        answer:
          "It varies by lender and instrument: appraisal, origination, and recording charges are common, lines of credit sometimes carry annual fees, and lenders that waive upfront costs often recover them if you close the line early. Ask for the full fee schedule, including what closing the account costs, before comparing anything else."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/refinance-break-even", label: "Compare against a cash-out refinance" },
      { href: "/calculators/mortgage-payment", label: "Estimate a fixed second-mortgage payment" }
    ],
    relatedPrograms: ["refinance", "conventional", "purchase"],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What you should know about home equity lines of credit (HELOC booklet)",
        url: "https://files.consumerfinance.gov/f/documents/cfpb_heloc-brochure.pdf"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is a home equity loan?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-106/"
      },
      {
        publisher: "Board of Governors of the Federal Reserve System",
        title: "What you should know about home equity lines of credit",
        url: "https://www.federalreserve.gov/pubs/equity/equity_english.htm"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "fha",
    heroImage: SCENARIO_IMAGES.purchase,
    navLabel: "FHA",
    h1: "FHA loans in Florida",
    title: "FHA Loans in Florida",
    description:
      "How FHA insurance changes the payment, who the program tends to serve, and the tradeoff to weigh against conventional.",
    eyebrow: "Program",
    summary:
      "An FHA loan is insured by the Federal Housing Administration. That insurance is why the program can be more flexible on credit and down payment than conventional financing — and it is also the cost you weigh against that flexibility, because FHA mortgage insurance behaves differently from conventional mortgage insurance.",
    mayFit: [
      "Your credit profile makes conventional pricing unattractive",
      "You have limited funds for a down payment",
      "You are buying a primary residence"
    ],
    exploreAlternativesIf: [
      "You are eligible for VA financing",
      "Your credit and down payment would make conventional cheaper over the time you plan to hold the loan",
      "You are buying a second home or investment property"
    ],
    howItWorks: [
      {
        heading: "FHA insures the lender, not you",
        body: "The insurance protects the lender against loss, which is what allows more flexible qualifying terms. You pay for it through an upfront premium and an annual premium collected monthly."
      },
      {
        heading: "The property has to qualify too",
        body: "FHA has minimum property standards. An appraiser evaluates the property against them, and required repairs can affect your timeline."
      },
      {
        heading: "The insurance duration matters",
        body: "How long FHA mortgage insurance remains on the loan depends on the terms in effect and your loan structure. This is the single most important thing to understand before choosing FHA over conventional, and it is worth working through with real numbers for your situation."
      }
    ],
    variables: [
      {
        label: "Mortgage insurance premiums",
        body: "Both the upfront and annual premium are set by HUD and change from time to time."
      },
      {
        label: "County loan limits",
        body: "FHA limits vary by county and are updated periodically."
      },
      {
        label: "Property condition",
        body: "Minimum property standards can require repairs before closing."
      },
      {
        label: "Lender overlays",
        body: "Lenders frequently apply requirements stricter than FHA's own."
      }
    ],
    faqs: [
      {
        question: "Is FHA always cheaper than conventional?",
        answer:
          "No. It depends on your credit profile, your down payment, and how long you keep the loan. For some borrowers conventional is less expensive overall; for others FHA clearly wins. The comparison is worth doing with your actual numbers."
      },
      {
        question: "Can I use FHA for an investment property?",
        answer:
          "FHA financing is intended for owner-occupied primary residences. Investment property financing follows a different path."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/mortgage-payment", label: "Estimate a payment with mortgage insurance" }
    ],
    relatedPrograms: ["conventional", "first-time-home-buyers"],
    sources: [
      {
        publisher: "U.S. Department of Housing and Urban Development",
        title: "FHA single family housing policy handbook",
        url: "https://www.hud.gov/program_offices/housing/sfh/handbook_4000-1"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: "FHA loan"
  },
  {
    slug: "va",
    heroImage: SCENARIO_IMAGES.purchase,
    navLabel: "VA",
    h1: "VA home loans in Florida",
    title: "VA Home Loans in Florida",
    description:
      "What VA eligibility provides, how entitlement and the funding fee work, and why the program is frequently underused.",
    eyebrow: "Program",
    summary:
      "A VA loan is guaranteed by the Department of Veterans Affairs and available to eligible service members, veterans, and certain surviving spouses. For borrowers who qualify it is often the strongest option available, and it is also the one most frequently left on the table because people assume it is slow or that sellers dislike it.",
    mayFit: [
      "You are an eligible service member, veteran, or surviving spouse",
      "You want to preserve cash at closing",
      "You want to avoid monthly mortgage insurance"
    ],
    exploreAlternativesIf: [
      "You are not eligible for the program",
      "You are buying an investment property, which the program does not serve"
    ],
    howItWorks: [
      {
        heading: "Eligibility comes from service",
        body: "You establish eligibility through a Certificate of Eligibility. Requirements depend on when and how you served."
      },
      {
        heading: "Entitlement determines your guaranty",
        body: "Entitlement is the amount VA guarantees on your behalf. It can be partially used by a prior loan and restored under certain conditions."
      },
      {
        heading: "The funding fee replaces monthly mortgage insurance",
        body: "Most borrowers pay a one-time funding fee, which can typically be financed. Some borrowers are exempt. There is no monthly mortgage insurance, which changes the payment comparison substantially."
      }
    ],
    variables: [
      {
        label: "Certificate of Eligibility",
        body: "Establishes that you qualify and what entitlement you have."
      },
      {
        label: "Funding fee",
        body: "Varies by service type, down payment, and whether you have used the benefit before. Exemptions exist."
      },
      {
        label: "Occupancy",
        body: "The program requires occupancy; it is not for investment property."
      },
      {
        label: "Property requirements",
        body: "VA has its own minimum property requirements assessed by the appraiser."
      }
    ],
    faqs: [
      {
        question: "Do VA loans take longer to close?",
        answer:
          "Not inherently. Timelines depend on the lender's process and the property, the same as any other loan. The reputation is largely outdated."
      },
      {
        question: "Can I use the benefit more than once?",
        answer:
          "Frequently yes. Entitlement can be restored under certain conditions, and remaining entitlement can sometimes support a second loan. Your specific situation determines the answer."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["conventional", "purchase"],
    sources: [
      {
        publisher: "U.S. Department of Veterans Affairs",
        title: "VA home loan programs",
        url: "https://www.va.gov/housing-assistance/home-loans/"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: "VA loan"
  },
  {
    slug: "usda",
    heroImage: SCENARIO_IMAGES.purchase,
    navLabel: "USDA",
    h1: "USDA loans and eligible Florida areas",
    title: "USDA Loans in Florida",
    description:
      "How USDA rural development financing works, and why the eligibility map surprises people.",
    eyebrow: "Program",
    summary:
      "USDA guaranteed loans support home purchases in designated rural areas, subject to household income limits. The word rural is misleading — many areas on the edge of Florida metros are eligible, and the only way to know is to check the current official map for the specific address.",
    mayFit: [
      "The property is in a currently eligible area",
      "Your household income is within the applicable limit",
      "You are buying a primary residence and want to minimize cash at closing"
    ],
    exploreAlternativesIf: [
      "The address is not in an eligible area",
      "Your household income exceeds the limit",
      "You are buying an investment property or second home"
    ],
    howItWorks: [
      {
        heading: "The address determines eligibility",
        body: "Eligibility is geographic and set by USDA. Maps are updated periodically, so we check the current official map for your specific address rather than relying on a general impression of an area."
      },
      {
        heading: "Household income is capped",
        body: "Limits vary by county and household size and are adjusted over time. The calculation includes household members beyond the borrowers in some cases."
      }
    ],
    variables: [
      {
        label: "Property location",
        body: "The single gating factor. Verified against the current official map."
      },
      { label: "Household income", body: "County- and size-dependent limits that change." },
      { label: "Guarantee fees", body: "USDA charges an upfront and an annual fee." }
    ],
    faqs: [
      {
        question: "Can you tell me if my address qualifies?",
        answer:
          "We check it against USDA's current official eligibility map together. We will not guess from a general sense of whether an area feels rural, because the boundaries frequently do not match intuition."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/affordability", label: "See an affordability range" }
    ],
    relatedPrograms: ["fha", "conventional"],
    sources: [
      {
        publisher: "U.S. Department of Agriculture",
        title: "Single family housing guaranteed loan program",
        url: "https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-guaranteed-loan-program"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: "USDA loan"
  },
  {
    slug: "jumbo",
    heroImage: SCENARIO_IMAGES.condo,
    navLabel: "Jumbo",
    h1: "Jumbo mortgage planning",
    title: "Jumbo Mortgages in Florida",
    description:
      "What changes when a loan exceeds conforming limits, and why jumbo guidelines vary so much between lenders.",
    eyebrow: "Program",
    summary:
      "A jumbo loan exceeds the conforming loan limit for its county. Because these loans are not eligible for purchase by the agencies, each investor sets its own guidelines — which is why jumbo terms differ far more between lenders than conforming terms do.",
    mayFit: [
      "Your loan amount exceeds the current conforming limit for the county",
      "You have documented reserves and a strong credit profile",
      "You want lender comparison to matter — with jumbo, it matters a great deal"
    ],
    exploreAlternativesIf: [
      "Structuring the transaction differently would bring the loan within conforming limits",
      "You have limited reserves, which jumbo guidelines weigh heavily"
    ],
    howItWorks: [
      {
        heading: "Guidelines are investor-specific",
        body: "There is no single jumbo rulebook. Reserve requirements, documentation, appraisal expectations, and pricing all vary by investor, which makes shopping genuinely valuable here."
      },
      {
        heading: "Reserves usually matter more than you expect",
        body: "Many jumbo programs require a specified number of months of payments in reserve after closing. This trips up borrowers who planned their cash around the down payment alone."
      }
    ],
    variables: [
      { label: "County conforming limit", body: "Determines whether the loan is jumbo at all." },
      { label: "Reserve requirements", body: "Often the binding constraint." },
      {
        label: "Property type",
        body: "Condos, unique properties, and high-value homes are scrutinized more closely."
      },
      {
        label: "Documentation depth",
        body: "Jumbo underwriting is typically more document-intensive."
      }
    ],
    faqs: [
      {
        question: "Are jumbo rates always higher?",
        answer:
          "Not necessarily. Jumbo pricing has at times been competitive with or better than conforming, depending on the investor and market conditions. It is worth comparing rather than assuming."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["conventional", "self-employed"],
    sources: [CFPB_MORTGAGE],
    requiresLenderPath: true,
    loanTypeForSchema: "Jumbo mortgage"
  },
  {
    slug: "investment-property",
    heroImage: SCENARIO_IMAGES.investment,
    navLabel: "Investment property",
    h1: "Financing an investment property",
    title: "Investment Property Financing in Florida",
    description:
      "How investment property financing differs, and which expenses belong in the model before you call something cash-flow positive.",
    eyebrow: "Investors",
    summary:
      "Investment property financing carries different down payment, reserve, and pricing expectations than a primary residence. The financing is usually the easier half of the analysis — the harder half is building an expense model honest enough to be worth acting on.",
    mayFit: [
      "You are buying a property you will not occupy",
      "You want the full expense stack modeled, not just rent minus mortgage",
      "You have reserves beyond the down payment"
    ],
    exploreAlternativesIf: [
      "You intend to occupy the property — occupancy is a representation you make to the lender, and misstating it is fraud",
      "You have not yet verified the local short-term rental rules for the strategy you have in mind"
    ],
    howItWorks: [
      {
        heading: "Occupancy changes everything",
        body: "Down payment, pricing, and reserve requirements all shift for non-owner-occupied property. Occupancy is a representation on your application, not a preference."
      },
      {
        heading: "Rental income treatment is program-specific",
        body: "Whether and how projected or existing rent counts toward qualifying varies by program and by whether there is a lease and a history."
      },
      {
        heading: "The expense model is where deals are won or lost",
        body: "Vacancy, management, maintenance, capital reserves, taxes, insurance, HOA, and utilities. Our investment calculator includes each of them because a model that omits capital reserves is not a model, it is optimism."
      }
    ],
    variables: [
      {
        label: "Down payment and reserves",
        body: "Typically higher than an owner-occupied purchase."
      },
      {
        label: "Rental income documentation",
        body: "A signed lease and a rent history are treated differently from a projection."
      },
      {
        label: "Insurance",
        body: "Landlord policies price differently, and Florida wind and flood exposure varies sharply by location."
      },
      {
        label: "Local rental regulation",
        body: "Short-term rental rules are municipal and change. Verify before you underwrite a strategy that depends on them."
      }
    ],
    faqs: [
      {
        question: "Will projected rent help me qualify?",
        answer:
          "Sometimes, depending on the program and the documentation available. It is never automatic and it is rarely the full amount."
      },
      {
        question: "Can I convert my primary residence into a rental?",
        answer:
          "Often yes, but the timing and your representations at application matter. Discuss it before you close, not after."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["conventional", "jumbo"],
    sources: [CFPB_MORTGAGE],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "self-employed",
    heroImage: SCENARIO_IMAGES.selfEmployed,
    navLabel: "Self-employed",
    h1: "Mortgage planning for self-employed borrowers",
    title: "Self-Employed Mortgage Planning in Florida",
    description:
      "How self-employment income is actually evaluated, and why the number on your tax return is the one that counts.",
    eyebrow: "Situations",
    summary:
      "Self-employment does not make a mortgage harder to obtain. It makes income calculation more involved, because lenders generally work from documented net income rather than gross revenue — and the deductions that reduce your tax bill also reduce the income used to qualify.",
    mayFit: [
      "You own a business, contract, or receive substantial 1099 income",
      "You want to understand how your income will be calculated before you apply",
      "You are planning ahead and can time a purchase around your filings"
    ],
    exploreAlternativesIf: [
      "Your business is very new — most programs expect a documented history"
    ],
    howItWorks: [
      {
        heading: "Documented net income is the starting point",
        body: "Lenders generally average net income across a period, with certain add-backs. Aggressive deductions lower that figure, which is the tension self-employed borrowers most often run into."
      },
      {
        heading: "History and stability matter",
        body: "Most programs look for a documented track record and evidence that the business continues to operate."
      },
      {
        heading: "Plan the timing",
        body: "If you know a purchase is coming, the conversation is worth having before you file, not after. That is a discussion with your accountant, and we are happy to be in it."
      }
    ],
    variables: [
      {
        label: "Business structure",
        body: "Sole proprietorship, partnership, S corporation, and C corporation are each analyzed differently."
      },
      {
        label: "Deductions",
        body: "They lower taxable income and therefore usually lower qualifying income."
      },
      { label: "Business history length", body: "Program requirements vary." },
      {
        label: "Program selection",
        body: "Documentation requirements differ meaningfully between programs."
      }
    ],
    faqs: [
      {
        question: "Can I use bank statements instead of tax returns?",
        answer:
          "Some programs evaluate income differently, but availability, terms, and pricing vary and change. Whether such a path exists for you depends on current lender offerings at the time you apply."
      },
      {
        question: "How many years of self-employment do I need?",
        answer:
          "It depends on the program and your broader profile. Some situations are workable with a shorter history than people expect."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/affordability", label: "See an affordability range" }
    ],
    relatedPrograms: ["conventional", "jumbo"],
    sources: [CFPB_MORTGAGE],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "condo",
    heroImage: SCENARIO_IMAGES.condo,
    navLabel: "Condo",
    h1: "Florida condo financing",
    title: "Condo Financing in Florida",
    description:
      "Why condo financing depends on the building as much as on you, and what to ask before you go under contract.",
    eyebrow: "Situations",
    summary:
      "With a condo, the lender underwrites the project as well as the borrower. In Florida this matters more than almost anywhere, because association finances, reserves, insurance, and structural inspection status can determine whether a building is financeable at all.",
    mayFit: [
      "You are considering a condominium or a unit in an association-governed community",
      "You want to know which questions to ask before your inspection period runs out"
    ],
    exploreAlternativesIf: [
      "You need certainty on a short timeline and the association is slow to produce documents"
    ],
    howItWorks: [
      {
        heading: "The project is reviewed",
        body: "Lenders evaluate the association's budget, reserves, insurance, litigation, delinquency rates, owner-occupancy mix, and single-entity ownership concentration. A unit can be perfect and still be difficult to finance because of the building."
      },
      {
        heading: "Florida-specific structural and reserve requirements matter",
        body: "Florida law regarding milestone structural inspections and reserve studies affects associations directly, and lender treatment of those items has evolved. Current requirements are checked at the time of your transaction."
      },
      {
        heading: "Ask early",
        body: "Association documents can take time to obtain. Requesting them at the start of your inspection period rather than the end is the single most useful thing you can do."
      }
    ],
    variables: [
      {
        label: "Association financial health",
        body: "Reserves, delinquencies, and budget adequacy."
      },
      { label: "Insurance", body: "Both master policy adequacy and your own unit coverage." },
      {
        label: "Special assessments",
        body: "Pending or recent assessments affect both financing and your carrying cost."
      },
      {
        label: "Litigation",
        body: "Certain kinds of pending litigation can make a project ineligible."
      },
      { label: "Owner-occupancy and investor concentration", body: "Both are evaluated." }
    ],
    faqs: [
      {
        question: "Why was my condo loan declined when I qualified?",
        answer:
          "Almost always the project rather than the borrower. Project eligibility is a separate review, which is why we ask about the association early."
      },
      {
        question: "What should I ask the association up front?",
        answer:
          "The current budget and reserve study, insurance certificates, any pending or recent special assessments, the status of any required structural inspection, and whether there is pending litigation."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/mortgage-payment", label: "Estimate a payment including HOA dues" }
    ],
    relatedPrograms: ["conventional", "fha"],
    sources: [CFPB_MORTGAGE],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "dscr",
    heroImage: SCENARIO_IMAGES.investment,
    navLabel: "DSCR",
    h1: "DSCR loans for Florida rental property",
    title: "DSCR Loans in Florida",
    description:
      "How a debt service coverage ratio is calculated, what it replaces, and where a DSCR loan costs an investor more than an agency loan would.",
    eyebrow: "Investors",
    summary:
      "A DSCR loan qualifies the property rather than the person. The lender compares the rent the property produces against the payment the loan would require, and the resulting ratio stands in for the tax returns, pay stubs, and debt-to-income calculation an agency loan runs on. That trade has a price, and it is not always the right one.",
    mayFit: [
      "You already have several financed properties and have reached the financed-property count an agency loan allows",
      "Your returns show depreciation and expense deductions that make your personal income look far thinner than your portfolio actually performs",
      "You are taking title in an LLC and want the financing structure to match",
      "The property has a signed lease or a documented rent history that supports the payment"
    ],
    exploreAlternativesIf: [
      "You will occupy any unit of the property — this structure is written as business-purpose credit on non-owner-occupied property",
      "Your documented personal income supports the loan comfortably, in which case an agency investment loan is usually cheaper",
      "The property is vacant, mid-renovation, or has no market rent an appraiser can support yet",
      "You expect to sell or refinance within a year or two and have not looked at the prepayment terms these programs commonly carry"
    ],
    howItWorks: [
      {
        heading: "The ratio replaces the income calculation",
        body: "A debt service coverage ratio divides the property's monthly rent by the property's monthly debt service — commonly principal, interest, taxes, insurance, and any association dues. Above one means the rent covers the payment; below one means it does not. That single figure does the work that pay stubs, tax returns, and your debt-to-income ratio would do on an agency loan. Whether the numerator is the signed lease, the appraiser's market rent opinion, or the lower of the two — and whether the denominator includes escrows — varies by lender and program."
      },
      {
        heading: "Rent is documented, not assumed",
        body: "Underwriting wants evidence. On agency loans, rental income is supported by an executed lease, Schedule E history, or an appraiser's market rent analysis on Form 1007 or 1025, and DSCR programs generally borrow the same evidence set even though they use it differently. Where a lease exceeds market rent, many lenders use the lower figure. Short-term rental income is treated differently again, and some lenders will not use it at all."
      },
      {
        heading: "The loan is usually business-purpose credit",
        body: "Under Regulation Z, credit extended to acquire, improve, or maintain rental property that is not owner-occupied is deemed to be for business purposes, and business-purpose credit is exempt from Regulation Z. That exemption is what makes this structure possible — and it is also why the consumer protections that attach to a primary-residence mortgage, including the ability-to-repay requirement, generally do not attach here. Occupancy is a representation you make, not a preference you can revise later."
      },
      {
        heading: "Pricing reflects the file you did not provide",
        body: "Nobody gives up the income documentation for free. Minimum ratio, down payment, reserves, prepayment terms, and pricing are set by each lender and investor rather than by an agency selling guide, which is why quotes on the identical file can differ far more than they would on a conforming loan. Comparing lenders is not a formality on this product."
      }
    ],
    variables: [
      {
        label: "The ratio itself",
        body: "Where your rent-to-payment ratio lands drives both eligibility and pricing. Minimums vary by lender, investor, and property type, and many programs price in tiers rather than applying one cutoff, so a stronger ratio can improve terms rather than merely pass a test."
      },
      {
        label: "How the rent is evidenced",
        body: "A signed lease with a payment history reads differently from an appraiser's market rent opinion on a vacant unit. Short-term rental history is its own conversation and not every lender will consider it."
      },
      {
        label: "Down payment and reserves",
        body: "Both are set by the investor rather than an agency guide, and both move pricing. Reserves are frequently the constraint investors discover late, after the down payment is already committed."
      },
      {
        label: "Prepayment terms",
        body: "Many programs in this space carry a prepayment penalty, often stepping down over the first few years. If you plan to sell or refinance soon, that structure can matter more to your total cost than the rate does."
      },
      {
        label: "Entity and title",
        body: "Closing in an LLC is common here and changes how title, insurance, and any personal guaranty are structured. Confirm the details with your closing agent and your own counsel before you commit to the structure."
      }
    ],
    faqs: [
      {
        question: "What ratio do I need?",
        answer:
          "There is no universal threshold, and any page that publishes one is describing a single lender's program rather than the market. Each lender and investor sets its own minimum, many price in tiers instead of applying a hard cutoff, and some will look at properties below break-even with compensating factors. What it actually depends on: the property type, the down payment, your reserves, your credit profile, and which investors that lender sells to. That is why we price a file against several programs rather than quote a number."
      },
      {
        question: "Does my personal income matter at all?",
        answer:
          "Usually not for the qualifying calculation — that is the point of the product. It can still matter indirectly. Credit profile, reserves, and experience owning rentals are commonly reviewed, and some lenders ask for a personal guaranty even when title is held in an entity."
      },
      {
        question: "Is this more expensive than a conventional investment property loan?",
        answer:
          "Frequently yes, because you are paying for documentation you did not provide and because these loans are sold to private investors rather than to Fannie Mae or Freddie Mac. But not always, and not by a fixed amount. If your tax returns support the loan, the agency path is worth pricing first. If they do not, the real comparison is between this and no financing at all."
      },
      {
        question: "Can I use projected short-term rental income?",
        answer:
          "Some lenders will, some will use only long-term market rent, and some will not finance a short-term rental at all. Local rules add a second layer: Florida municipalities regulate short-term rentals differently and those rules change. Verify the rules for the specific address before you underwrite a strategy that depends on them."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["investment-property", "bank-statement", "conventional"],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Regulation Z § 1026.3 — Exempt transactions",
        url: "https://www.consumerfinance.gov/rules-policy/regulations/1026/3/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Official interpretations to § 1026.3 — non-owner-occupied rental property",
        url: "https://www.consumerfinance.gov/rules-policy/regulations/1026/interp-3/"
      },
      {
        publisher: "Fannie Mae",
        title: "Selling Guide B3-3.8-01, Rental Income",
        url: "https://selling-guide.fanniemae.com/sel/b3-3.8-01/rental-income"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "bank-statement",
    heroImage: SCENARIO_IMAGES.selfEmployed,
    navLabel: "Bank statement",
    h1: "Bank statement loans for self-employed borrowers",
    title: "Bank Statement Loans in Florida",
    description:
      "How deposit-based income calculation works, what an expense factor does to your qualifying income, and when tax returns are still the better path.",
    eyebrow: "Situations",
    summary:
      "A bank statement loan calculates qualifying income from deposits into your business or personal accounts rather than from the net income reported on your tax returns. It exists for one specific problem: a profitable business whose entirely legitimate deductions make the owner look, on paper, like they earn a fraction of what they actually take in.",
    mayFit: [
      "You are self-employed and your returns show net income well below what the business produces",
      "Your deductions are legitimate and you have no intention of changing how you file in order to borrow",
      "You have a settled business with consistent deposits you can document over a meaningful period",
      "An agency loan already came back short on income and you want the next option priced honestly"
    ],
    exploreAlternativesIf: [
      "Your tax returns already support the loan — there is no reason to pay for a workaround you do not need",
      "Your business is new enough that there is not yet a deposit history to average",
      "Your deposits are heavily mixed with personal transfers, loan proceeds, or one-time events that underwriting will strip out anyway",
      "You could reach the same loan amount by paying down a revolving balance, which is usually cheaper than changing loan type"
    ],
    howItWorks: [
      {
        heading: "Deposits replace the tax return, not the verification",
        body: "Regulation Z's ability-to-repay standard requires a creditor to verify the income or assets it relies on using third-party records that provide reasonably reliable evidence, and it names financial institution records among the acceptable forms. A bank statement loan is not an unverified loan. It substitutes one third-party record for another; what changes is which number the underwriter ends up using."
      },
      {
        heading: "Underwriting scrubs the deposits before it averages them",
        body: "Transfers between your own accounts, loan proceeds, tax refunds, asset sales, and other non-revenue items are removed. What survives is treated as gross business revenue across the period reviewed — commonly twelve or twenty-four months of statements, though the period and the treatment vary by lender."
      },
      {
        heading: "An expense factor turns revenue into income",
        body: "Because statements show money in rather than profit, lenders apply an expense factor: a percentage assumed to be the cost of running the business, subtracted before qualifying income is set. Some programs use a fixed factor, some vary it by industry, and some will accept a letter from your accountant supporting a lower one. This one assumption usually moves your approvable loan amount more than the interest rate does."
      },
      {
        heading: "Everything else is underwritten normally",
        body: "Credit, assets, reserves, the property, and the appraisal are reviewed the way they would be on any other loan. The bank statement treatment addresses how income is calculated and nothing else, which is worth saying plainly because the product is often described as though it relaxed everything."
      }
    ],
    variables: [
      {
        label: "The expense factor",
        body: "The assumed cost of doing business, subtracted before your qualifying income is set. A few percentage points of difference can change the loan amount materially, which makes the program choice as consequential as the lender choice."
      },
      {
        label: "Which accounts, and how many months",
        body: "Business accounts and personal accounts are treated differently, and lenders differ on the review period. A seasonal business can look very different over twelve months than over twenty-four."
      },
      {
        label: "Deposit consistency",
        body: "Steady deposits read as stable income. Large irregular deposits invite documentation requests and are sometimes excluded from the average entirely."
      },
      {
        label: "Ownership percentage",
        body: "If you own part of a business rather than all of it, many programs prorate deposits to your ownership share. Partners are regularly surprised by this."
      },
      {
        label: "What you can actually document",
        body: "An accountant's letter, a current business licence, and a profit-and-loss statement are commonly requested. Which programs a lender offers, and on what terms, varies and changes."
      }
    ],
    faqs: [
      {
        question: "Is this the same as a stated income loan?",
        answer:
          "No. Stated income meant taking the borrower's word for the number. Here the deposits are evidenced with statements issued by the financial institution and the calculation is performed by an underwriter. It is a different income calculation, not the absence of one."
      },
      {
        question: "How much more does it cost than a conventional loan?",
        answer:
          "It generally prices above an agency loan, because these loans are held in portfolio or sold to private investors who each set their own terms rather than delivered to Fannie Mae or Freddie Mac. How much above depends on the lender, your credit profile, the down payment, and market conditions at the time. The comparison worth running is not rate against rate — it is total cost against the loan amount each path actually supports."
      },
      {
        question: "Should I just report more income next year instead?",
        answer:
          "Sometimes that is the right answer, and sometimes it is expensive tax advice wearing a mortgage costume. Reporting more income raises your tax bill; the question is whether the financing savings exceed the additional tax over the years you expect to hold the loan. That is a conversation with your accountant, and we are glad to be in it."
      },
      {
        question: "Can I use personal statements if business revenue lands in my personal account?",
        answer:
          "Often yes, though the treatment differs and the scrub tends to be stricter, because a personal account mixes revenue with transfers and gifts. Bring the accounts as they actually are. Reorganising them a month before an application rarely helps and sometimes makes the history harder to read."
      }
    ],
    relatedCalculators: [
      { href: "/calculators/affordability", label: "See an affordability range" }
    ],
    relatedPrograms: ["self-employed", "dscr", "jumbo"],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Regulation Z § 1026.43 — Minimum standards for transactions secured by a dwelling",
        url: "https://www.ecfr.gov/current/title-12/chapter-X/part-1026/subpart-E/section-1026.43"
      },
      {
        publisher: "Fannie Mae",
        title:
          "Selling Guide B3-3.5-01, Underwriting Factors and Documentation for a Self-Employed Borrower",
        url: "https://selling-guide.fanniemae.com/sel/b3-3.5-01/underwriting-factors-and-documentation-self-employed-borrower"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: null
  },
  {
    slug: "renovation",
    heroImage: SCENARIO_IMAGES.construction,
    navLabel: "Renovation",
    h1: "Renovation loans in Florida",
    title: "Renovation Loans in Florida",
    description:
      "How FHA 203(k) and conventional renovation loans finance repairs into the mortgage, and where the draw process actually slows a project down.",
    eyebrow: "Program",
    summary:
      "A renovation loan sizes the mortgage against what a property will be worth once the work is finished rather than what it is worth today, and places the repair money in an escrow account at closing. It is the answer to a house that will not appraise in its current condition — and the process around it is considerably more structured than most buyers expect.",
    mayFit: [
      "The house you want needs work you cannot fund out of pocket after closing",
      "The property will not pass an appraisal as-is and the seller will not make the repairs",
      "You already own the home and want repairs financed at mortgage terms rather than on a card or a personal loan",
      "You are buying a dated property in a location you want, and the renovation is the entire point of the purchase"
    ],
    exploreAlternativesIf: [
      "The work is cosmetic and small enough to pay for after closing without a structured draw process",
      "You need to close quickly — bids, plans, and contractor approval add time before underwriting can even finish",
      "You intend to do the work yourself, which programs restrict",
      "The property is effectively a teardown, which is construction financing rather than renovation financing"
    ],
    howItWorks: [
      {
        heading: "The appraisal is written subject to the work",
        body: "An appraiser values the property as completed, based on the specific scope of work in your file. That after-improved value is what the loan is sized against, which is the whole reason the structure exists. Change the scope and the value opinion has to be revisited with it."
      },
      {
        heading: "The repair money goes into escrow, not to you",
        body: "At closing, the renovation portion of the loan is set aside in an escrow account the lender controls. It is not disbursed to you at the table and it is not working capital."
      },
      {
        heading: "Funds release in draws against inspected work",
        body: "Contractors are paid in stages. HUD describes the FHA 203(k) sequence directly: a consultant inspects each phase and certifies the work, then the lender issues a two-party check payable to the borrower and the contractor, repeating until the project is complete and the remaining escrow is released. On the Standard 203(k) a HUD-approved consultant prepares the work write-up and cost estimate; on the Limited version a consultant is optional. Fannie Mae's HomeStyle Renovation and Freddie Mac's CHOICERenovation run on the same principle with their own procedures — Freddie describes CHOICERenovation as financing purchase and renovation in a single closing so there is no separate interim construction loan to pay off."
      },
      {
        heading: "There is a clock on completion",
        body: "Fannie Mae's HomeStyle Renovation guidance requires the work to be finished within a defined period after closing, with a limited extension available on request, and lenders deliver the loan with recourse until it is done. That is why your contractor's capacity and willingness to work on a schedule are underwritten rather than assumed."
      }
    ],
    variables: [
      {
        label: "Scope of work and the bid",
        body: "The written scope drives the appraisal, the escrow amount, and the timeline. Vague or incomplete bids are the single most common cause of delay on these files."
      },
      {
        label: "Which program",
        body: "FHA 203(k) comes in a Limited and a Standard version with different ceilings and different consultant requirements, and HUD updates those figures. HomeStyle Renovation and CHOICERenovation are the conventional equivalents. Eligible property types, occupancy, and allowable improvements differ across all of them."
      },
      {
        label: "Your contractor",
        body: "Licensing, insurance, financial capacity, and experience working against a draw schedule are all reviewed. A contractor who has never been paid in inspected stages is a genuine risk to your timeline."
      },
      {
        label: "Contingency reserve",
        body: "Programs require a reserve for overruns, funded from the loan. It protects the project and it also raises the amount you borrow and the payment you carry."
      },
      {
        label: "As-completed value",
        body: "If the appraiser's after-improved opinion does not support the total, the gap is yours to cover in cash or the scope has to shrink. This is where over-improving for a neighbourhood shows up."
      }
    ],
    faqs: [
      {
        question: "Can I do the work myself to save money?",
        answer:
          "Programs restrict self-help work and generally expect licensed contractors, with any exception documented in advance rather than discovered at draw time. Planning to swing the hammer yourself and sort out the paperwork later is a reliable way to stall a file."
      },
      {
        question: "How much can I finance for the repairs?",
        answer:
          "It depends on the program and on the after-improved appraised value. HUD sets separate ceilings for the Limited and Standard versions of 203(k) and updates them; the conventional programs work from a share of the completed value. We check the current published figures for the program you are actually using rather than printing a number that ages badly."
      },
      {
        question: "Is this slower than a normal purchase?",
        answer:
          "Usually, yes. Bids, plans, contractor approval, and a subject-to appraisal all have to happen before underwriting can clear the file. Negotiate that time into your contract rather than discovering it during the inspection period."
      },
      {
        question: "Can I use a renovation loan on an investment property?",
        answer:
          "It depends on the program. Freddie Mac describes CHOICERenovation as available for primary residences, second homes, and one-to-four unit investment properties; FHA financing is for owner-occupied primary residences. Which of these a given lender actually offers varies, so confirm it before you go under contract."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["construction", "fha", "conventional"],
    sources: [
      {
        publisher: "U.S. Department of Housing and Urban Development",
        title: "203(k) Rehabilitation Mortgage Insurance Program types",
        url: "https://www.hud.gov/hud-partners/single-family-203k"
      },
      {
        publisher: "Fannie Mae",
        title: "Selling Guide B5-3.2-01, HomeStyle Renovation Mortgages",
        url: "https://selling-guide.fanniemae.com/sel/b5-3.2-01/homestyle-renovation-mortgages"
      },
      {
        publisher: "Freddie Mac",
        title: "CHOICERenovation Mortgages",
        url: "https://sf.freddiemac.com/working-with-us/origination-underwriting/mortgage-products/choicerenovation"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: "Renovation mortgage"
  },
  {
    slug: "construction",
    heroImage: SCENARIO_IMAGES.construction,
    navLabel: "Construction",
    h1: "Construction-to-permanent financing in Florida",
    title: "Construction Loans in Florida",
    description:
      "How a single-close construction loan converts to a permanent mortgage, how draws and interest during the build work, and what a two-close structure costs you.",
    eyebrow: "Program",
    summary:
      "Construction-to-permanent financing pays for a house that does not exist yet and then becomes the mortgage on it. The structure matters more than the headline rate: whether you close once or twice determines how many sets of closing costs you pay, how much rate risk you carry through the build, and whether you have to be underwritten again when the house is finished.",
    mayFit: [
      "You are building on a lot you already own or are acquiring as part of the same transaction",
      "You want one closing rather than a construction loan followed by a separate refinance",
      "You have a builder with a fixed-price contract, complete plans, and a realistic schedule",
      "You want the permanent terms settled before the first shovel goes in the ground"
    ],
    exploreAlternativesIf: [
      "You are buying a finished spec home from a builder — that is an ordinary purchase transaction",
      "The work is repair or remodel of an existing house, which is renovation financing",
      "Your builder is unwilling to work within a draw schedule and an inspection process",
      "Your plans and budget are not settled — the loan is sized against the cost breakdown, so a moving budget is a moving loan"
    ],
    howItWorks: [
      {
        heading: "One closing or two, and the choice is structural",
        body: "In a single-closing transaction the construction financing and the permanent mortgage close at the same time on the same set of documents, and the loan converts to permanent financing when the house is complete. In a two-closing structure the interim construction loan is its own transaction, later paid off by a separate permanent mortgage: a second closing, a second set of costs, and a second underwrite at whatever terms exist on that day. Fannie Mae and Freddie Mac both address single-close and two-close paths, and they are not interchangeable."
      },
      {
        heading: "The loan is sized against cost or completed value, whichever is lower",
        body: "Fannie Mae's single-closing guidance sets the property value used for loan-to-value at the lesser of the total acquisition cost — land plus construction — or the appraised value of the completed property. This is where borrowers are most often surprised: an expensive build in a modest neighbourhood is limited by the appraisal, and the difference between the two figures comes out of your own funds."
      },
      {
        heading: "Money releases in draws against verified progress",
        body: "You do not receive the loan amount at closing. The lender disburses in stages as work is completed and verified, typically with a title update at each draw to confirm no liens have attached. Interest is commonly charged only on what has actually been advanced, which is why Regulation Z carries a dedicated appendix for multiple-advance construction loans where the amounts or timing of advances are unknown at consummation — it also addresses how interest reserves are handled."
      },
      {
        heading: "Conversion is the part to understand before you sign",
        body: "On a single close, the loan modifies to its permanent terms when the house is finished. How the permanent rate is established, whether a float-down exists, and whether credit documents must be refreshed before conversion all vary by lender and program — Fannie Mae's guidance addresses requalification and credit document aging for exactly this reason. Ask what happens at conversion before construction starts, not after."
      }
    ],
    variables: [
      {
        label: "Single close versus two close",
        body: "Drives closing costs, rate exposure through the build, and whether you are underwritten again at the end. It is the first question, not a detail to settle later."
      },
      {
        label: "How the permanent rate is set",
        body: "Extended locks, float-downs, and rate-set-at-conversion are all real structures with different costs. Over a build measured in months rather than weeks, the difference between them is not small."
      },
      {
        label: "Builder qualification",
        body: "Lenders review the builder's licence, insurance, financial capacity, and track record. A builder who cannot be approved ends the conversation regardless of how strong your own file is."
      },
      {
        label: "Cost breakdown and contingency",
        body: "The line-item budget drives the draw schedule. Programs expect a contingency for overruns, and anything beyond it is generally funded by you rather than by the loan."
      },
      {
        label: "Land equity",
        body: "If you already own the lot, its value can often count toward your equity. Fannie Mae's single-closing guidance treats a borrower who already owns the lot differently from one acquiring it, and how long you have owned it matters."
      }
    ],
    faqs: [
      {
        question: "What do I pay each month during construction?",
        answer:
          "Commonly interest on the amount drawn to date, which rises as the build progresses. Whether an interest reserve is built into the loan instead varies by lender. Regulation Z's appendix for multiple-advance loans exists precisely because these payments cannot be stated exactly at closing, so expect an estimate with disclosed assumptions rather than a fixed schedule."
      },
      {
        question: "Can I act as my own general contractor?",
        answer:
          "Rarely, and it is entirely program- and lender-specific. Most programs expect a licensed general contractor with a documented track record, because the lender is releasing money against a schedule and needs someone accountable for it."
      },
      {
        question: "What happens if the build runs over budget?",
        answer:
          "The contingency absorbs part of it. Beyond that, overruns are generally yours to fund in cash — the loan amount was established at closing, and increasing it means re-underwriting if it is possible at all. This is the strongest practical argument for a fixed-price contract rather than a cost-plus one."
      },
      {
        question: "Can I build on a lot I already own free and clear?",
        answer:
          "Frequently yes, and the lot equity commonly serves as part or all of your down payment. Fannie Mae's single-closing guidance handles the already-owned-lot case as a refinance rather than a purchase, which changes the paperwork more than it changes the outcome."
      }
    ],
    relatedCalculators: [{ href: "/calculators/mortgage-payment", label: "Estimate a payment" }],
    relatedPrograms: ["land", "renovation", "conventional"],
    sources: [
      {
        publisher: "Fannie Mae",
        title:
          "Selling Guide B5-3.1-02, Conversion of Construction-to-Permanent Financing: Single-Closing Transactions",
        url: "https://selling-guide.fanniemae.com/sel/b5-3.1-02/conversion-construction-permanent-financing-single-closing-transactions"
      },
      {
        publisher: "Freddie Mac",
        title: "Construction to Permanent Mortgages",
        url: "https://sf.freddiemac.com/working-with-us/origination-underwriting/mortgage-products/construction-to-permanent-mortgages"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Regulation Z Appendix D — Multiple-Advance Construction Loans",
        url: "https://www.consumerfinance.gov/rules-policy/regulations/1026/interp-d/"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: "Construction-to-permanent mortgage"
  },
  {
    slug: "land",
    heroImage: SCENARIO_IMAGES.construction,
    navLabel: "Land and lot",
    h1: "Land and lot loans in Florida",
    title: "Land and Lot Loans in Florida",
    description:
      "Why financing vacant land prices differently from financing a house, what raw and improved land mean to a lender, and when to skip the lot loan entirely.",
    eyebrow: "Program",
    summary:
      "A loan on vacant land is not a mortgage on a home, and lenders do not treat it as one. Land produces no income, costs money to hold, and is far harder to sell after a default, so it is financed on shorter terms, with more money down, and usually by institutions holding the loan on their own books rather than delivering it to an agency.",
    mayFit: [
      "You have found a homesite you want to hold before you are ready to build",
      "You are buying acreage adjacent to property you already own",
      "The location is the opportunity and the timing of construction is genuinely unsettled",
      "You have substantial funds for the down payment and reserves to carry the payment while the parcel sits"
    ],
    exploreAlternativesIf: [
      "You intend to build soon — construction-to-permanent financing that includes land acquisition avoids paying to finance the same dirt twice",
      "The parcel has no recorded legal access, no utilities, or an unresolved zoning or wetland question; those are underwriting problems before they are financing problems",
      "You are relying on refinancing this loan into construction financing later and have not confirmed that path exists",
      "The seller is willing to finance the parcel and you have not compared that against an institutional loan"
    ],
    howItWorks: [
      {
        heading: "Regulators treat land as a different risk class",
        body: "The interagency guidelines for real estate lending policies that federal banking regulators apply set supervisory loan-to-value limits by loan category, and raw land is listed separately with a lower limit than owner-occupied one-to-four family residential property. That is not a single conservative lender; it is the framework the lender's own examiners work from, and it is the structural reason land requires more money down than a house does."
      },
      {
        heading: "Raw, unimproved, and improved are not interchangeable words",
        body: "A recorded lot in a platted subdivision with paved access, power at the street, and water and sewer available is a fundamentally different loan from acreage with no road frontage and no utilities. The further a parcel sits from buildable, the shorter the term, the larger the down payment, and the smaller the set of institutions willing to look at it."
      },
      {
        heading: "The loan usually stays on the lender's own books",
        body: "Vacant land is generally not eligible for delivery to Fannie Mae or Freddie Mac the way a mortgage on a dwelling is. These are typically portfolio products at banks and credit unions, and each institution writes its own rules. That is precisely why terms differ so widely between them and why shopping is worth real effort here rather than being a formality."
      },
      {
        heading: "Terms are shorter than a mortgage, and often do not fully amortize",
        body: "Lot loans commonly run considerably shorter than a thirty-year mortgage, and some carry a balloon rather than amortizing to zero. Plan the exit — build, refinance, or sell — before you close, because the structure of the loan already assumes you have one."
      }
    ],
    variables: [
      {
        label: "Improvement level",
        body: "Utilities, paved access, and recorded plat status move a parcel between lender categories, and the category changes essentially every term of the loan."
      },
      {
        label: "Legal access and easements",
        body: "A parcel without recorded legal access is not financeable at most institutions, however it looks on a map. Confirm access from the title work, not from the listing."
      },
      {
        label: "Zoning and land use",
        body: "What the county permits you to build governs the value an appraiser can support. In Florida, wetland delineation and environmental review are frequently the gating item rather than zoning itself."
      },
      {
        label: "Appraisal comparables",
        body: "Land appraisals rely on fewer and less similar sales than home appraisals do. Values are therefore less predictable, which is part of why lenders price the risk the way they do."
      },
      {
        label: "Your exit plan",
        body: "Whether you intend to build, hold, or sell determines whether a lot loan is even the right instrument. Building within the year usually points to the construction path instead."
      }
    ],
    faqs: [
      {
        question: "How much do I need to put down on land?",
        answer:
          "More than on a house, and how much more depends on the parcel and the institution. The supervisory guidelines examiners apply set a lower loan-to-value limit for raw land than for a one-to-four family home, and individual lenders commonly require more equity than the supervisory figure. Anyone quoting a single number without knowing whether the parcel has utilities and recorded legal access is guessing."
      },
      {
        question: "Can I get a thirty-year fixed loan on a lot?",
        answer:
          "Usually not. Lot loans are typically written on shorter terms and some carry a balloon rather than fully amortizing. That is a function of who holds the loan and how regulators classify the collateral, not a judgement about your credit."
      },
      {
        question: "Should I buy the lot now and build later?",
        answer:
          "It depends on how far off the build is. Financing the land and then financing construction separately means two transactions and two sets of costs; construction-to-permanent financing that includes the land acquisition means one. If you are ready to build, the combined path is usually cheaper. If the parcel is the opportunity and the build is years away, a lot loan is doing a job the construction loan cannot."
      },
      {
        question: "Does owning the lot outright help when I finally build?",
        answer:
          "Frequently yes. Lot equity can count toward the equity in a construction-to-permanent transaction, and Fannie Mae's single-closing guidance addresses the case where the borrower already owns the lot. How the equity is credited depends on how and when you acquired the land, so bring the purchase documents to the conversation."
      }
    ],
    relatedCalculators: [],
    relatedPrograms: ["construction", "investment-property", "purchase"],
    sources: [
      {
        publisher: "Office of the Comptroller of the Currency",
        title:
          "12 CFR part 34, appendix A to subpart D — Interagency Guidelines for Real Estate Lending Policies",
        url: "https://www.ecfr.gov/current/title-12/chapter-I/part-34/subpart-D/appendix-Appendix%20A%20to%20Subpart%20D%20of%20Part%2034"
      },
      {
        publisher: "Fannie Mae",
        title:
          "Selling Guide B5-3.1-02, Conversion of Construction-to-Permanent Financing: Single-Closing Transactions",
        url: "https://selling-guide.fanniemae.com/sel/b5-3.1-02/conversion-construction-permanent-financing-single-closing-transactions"
      }
    ],
    requiresLenderPath: true,
    loanTypeForSchema: null
  }
];

export function programBySlug(slug: string): Program | undefined {
  return PROGRAMS.find((program) => program.slug === slug);
}
