import type { Metadata } from "next";
import { Section, SectionHeading, Disclosure } from "@/components/ui";
import { RendPropDemo } from "@/components/rendprop/demo";
import { pageMetadata } from "@/lib/metadata";

export const metadata: Metadata = pageMetadata({
  title: "RendProp walkthrough",
  description:
    "An illustrative click-through of the RendProp pipeline: project, capture, room tagging, transformations, before-and-after review, approval, and a shared tour.",
  path: "/rendprop/demo",
  noIndex: true
});

/**
 * The walkthrough is a client component because the whole point is that a
 * reader can drive it. Nothing it does touches the network: no project is
 * created, no file is uploaded, no job is enqueued, and no provider exists to
 * call. It is a product explanation you can operate, not a trial.
 */
export default function RendPropDemoPage() {
  return (
    <Section width="default" pad="head">
      <SectionHeading
        as="h1"
        eyebrow="Illustrative walkthrough"
        title="How RendProp would work, end to end"
        gradientWord="end to end"
        description="Every screen below is drawn in your browser from sample data. No media provider is connected, so RendProp cannot currently process a real walkthrough — this shows the shape of the product, not a working pipeline."
      />
      <RendPropDemo />
      <Disclosure
        headline="Everything on this page is illustrative."
        body="The addresses are reserved example values, the visuals are diagrams rather than photographs, and no image here was generated by any model. Any altered imagery in the real product carries a visible label; that labelling is demonstrated here exactly as it would ship."
        version="rendprop-disclosure@0.1.0"
      />
    </Section>
  );
}
