import type { Article } from "./types";

/**
 * First-time buyer cluster. Written for a Florida buyer who has never done
 * this before and does not know which parts of the folklore are true. Every
 * mutable figure points at its primary source instead of being stated.
 */
export const FIRST_TIME_ARTICLES: Article[] = [
  {
    slug: "preapproval-vs-prequalification",
    category: "first-time",
    title: "Preapproval vs. Prequalification in Florida",
    description:
      "Prequalification is an estimate; preapproval is a verified review. Here is the real difference and why Florida listing agents only take one of them seriously.",
    h1: "Preapproval vs. prequalification: the difference that decides whether your offer gets read",
    answerSummary:
      "A prequalification is an estimate built from what you tell a lender, usually without documents. A preapproval means an underwriting-grade review of your credit, income, and assets has actually happened. Florida listing agents weigh a preapproval far more heavily because it shows a lender has verified your file, not just heard about it. In a multiple-offer situation, the difference can decide which contract the seller signs.",
    sections: [
      {
        heading: "What each word actually means",
        paragraphs: [
          "Neither term has a single legal definition, and the Consumer Financial Protection Bureau is blunt about this: different lenders use the words differently, and neither letter is a commitment to lend. What matters is not the label on the letter but what the lender did before issuing it.",
          "In practice, a prequalification is a conversation. You describe your income, debts, and savings; the lender runs the arithmetic and tells you roughly what you could borrow if everything you said checks out. It often does not involve a credit pull, and it almost never involves documents. It is genuinely useful for one thing: deciding whether it is worth going further.",
          "A preapproval is a file. You hand over pay stubs, W-2s or tax returns, and bank statements; the lender pulls credit, runs the file through automated underwriting, and in the stronger versions has a human underwriter review it. The letter that comes out the other side says a specific lender examined specific evidence and is prepared to lend a specific amount, subject to a property, an appraisal, and no material change in your finances."
        ]
      },
      {
        heading: "Why the listing agent cares",
        paragraphs: [
          "When a Florida listing agent receives three offers, their first job is to figure out which buyers will actually make it to the closing table. A contract that falls apart during the loan approval period costs the seller weeks of market time, and in a slowing neighborhood that can mean relisting at a lower price. So agents triage.",
          "A prequalification letter tells the agent almost nothing, because it is built on unverified statements. A preapproval letter tells the agent that the riskiest part of your financing — the borrower — has already been examined. Agents also routinely call the loan officer named on the letter to ask, in so many words, how real it is. A letter from a lender who verified documents survives that call; a letter generated by an online form in four minutes does not.",
          "This matters more in Florida than in many markets because the properties themselves add financing risk: condos need association reviews, older roofs complicate insurance, and flood zones add a required policy. A seller's agent who knows the property will have friction wants a buyer whose personal file has none."
        ]
      },
      {
        heading: "What a strong preapproval file looks like",
        paragraphs: [
          "The strength of a preapproval comes from what was verified. Before you shop, a thorough lender or broker will want the documents that underwriting will eventually demand anyway — collecting them early is how surprises get found while they are still cheap to fix."
        ],
        bullets: [
          "Recent pay stubs and two years of W-2s, or tax returns if you are self-employed",
          "Two months of statements for the accounts your down payment and closing funds will come from",
          "A credit report actually pulled, not a score you looked up yourself",
          "An automated underwriting decision (and ideally a human review) rather than a calculator result",
          "A letter that states the loan type, the verified amount, and an expiration date"
        ]
      },
      {
        heading: "Timing: when to get preapproved and how long it lasts",
        paragraphs: [
          "Get preapproved before you tour homes, not after you fall in love with one. Florida contracts move fast — an offer on the standard Florida Realtors/Florida Bar contract typically commits you to applying for financing within days of signing — and scrambling to assemble a file after your offer is accepted is how buyers blow deadlines.",
          "Preapproval letters expire, usually within 60 to 90 days, because the credit report and documents behind them go stale. If your search runs long, the lender refreshes the file. That is routine. What is not routine is your finances changing underneath the letter: a new car loan, a job change, or a large unexplained deposit can invalidate the analysis the letter was based on, so keep your financial life boring between preapproval and closing.",
          "One more distinction worth knowing: submitting a full application on a specific property is what triggers the lender's obligation to send you a Loan Estimate within three business days. A preapproval is the step before that — it makes the eventual application fast, because most of the work is already done.",
          "As a brokerage, TRACT arranges financing through wholesale lenders rather than making loans itself, which means a preapproval assembled with a broker can be shopped across multiple lenders without rebuilding the file each time. The verification work is the asset; the letter is just its receipt."
        ]
      }
    ],
    faqs: [
      {
        question: "Does a preapproval guarantee my loan will close?",
        answer:
          "No. A preapproval covers you as a borrower, not the property. The appraisal, title work, insurance, and (for condos) the association review all happen after you are under contract, and any of them can raise issues. A preapproval removes the largest source of financing risk, but final approval only comes once the whole file — borrower and property — clears underwriting."
      },
      {
        question: "Does getting preapproved hurt my credit score?",
        answer:
          "A preapproval involves a hard credit inquiry, which can have a small, temporary effect. Credit scoring models treat multiple mortgage inquiries within a short shopping window as a single event, so comparing lenders within that window does not multiply the impact. The CFPB's guidance on shopping for a mortgage covers how this works."
      },
      {
        question: "Can a seller's agent really tell the letters apart?",
        answer:
          "Usually, yes. Experienced agents read the letter for whether documents were verified and an automated underwriting decision was run, and many call the loan officer to probe. A vague letter with no lender contact, no loan type, and no expiration reads as a prequalification no matter what the heading says."
      },
      {
        question: "Should I get preapproved by more than one lender?",
        answer:
          "You can, and comparing offers is smart — but you do not need five full preapprovals to shop. One verified file establishes your credibility with sellers; from there, comparing Loan Estimates after application is how you compare actual pricing. Working with a broker accomplishes the comparison across lenders with a single file."
      }
    ],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What's the difference between a prequalification letter and a preapproval letter?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-prequalification-letter-and-a-preapproval-letter-en-127/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is a Loan Estimate?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-loan-estimate-en-1995/"
      }
    ],
    related: [
      { href: "/mortgage/first-time-home-buyers", label: "First-time home buyer programs" },
      { href: "/calculators/affordability", label: "Affordability calculator" },
      { href: "/resources/loan-estimate-explained", label: "How to read a Loan Estimate" },
      { href: "/resources/closing-timeline-florida", label: "Florida closing timeline" },
      { href: "/plan", label: "Start a preapproval plan" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "down-payment-how-much",
    category: "first-time",
    title: "How Much Down Payment Do You Really Need in Florida?",
    description:
      "The 20 percent rule is folklore. What conventional, FHA, VA, and USDA loans conceptually require, and the real tradeoffs of putting less down on a Florida home.",
    h1: "How much down payment do you actually need? Less than the folklore says",
    answerSummary:
      "You do not need 20 percent down to buy a home. Conventional programs exist with low single-digit minimums, FHA is built specifically for modest down payments, and VA and USDA loans can require no down payment at all for eligible borrowers. Twenty percent is simply the point where conventional loans drop private mortgage insurance. The real question is not the minimum — it is the tradeoff between a bigger payment now and a bigger cushion later.",
    sections: [
      {
        heading: "Where the 20 percent myth comes from",
        paragraphs: [
          "Twenty percent was never the entry price of homeownership. It is the threshold at which a conventional loan no longer requires private mortgage insurance — the point where the lender's exposure drops enough that the extra insurance policy on the loan becomes unnecessary. Somewhere along the way, a pricing boundary got repeated into a prerequisite, and it now stops renters who could buy from ever asking a lender the question.",
          "The Consumer Financial Protection Bureau, which regulates mortgage disclosures, describes PMI as insurance a lender may require on a conventional loan when the down payment is under 20 percent of the purchase price. That is the entire fact behind the myth. It says nothing about whether you can get a loan with less down — you can — only about whether that loan carries mortgage insurance."
        ]
      },
      {
        heading: "What the major program families conceptually require",
        paragraphs: [
          "Every program family approaches the down payment differently, and the specific minimums are program parameters that change — so check the current figures with the agency or through your loan officer rather than trusting a blog's numbers. Conceptually, the landscape looks like this:"
        ],
        bullets: [
          "Conventional (Fannie Mae / Freddie Mac): low-down-payment options exist, including programs like Fannie Mae's HomeReady aimed at lower-income buyers; under 20 percent down, expect PMI until you build enough equity",
          "FHA: designed around modest down payments and more flexible credit, in exchange for FHA mortgage insurance premiums; check current requirements through your lender or HUD",
          "VA: eligible veterans, service members, and some surviving spouses can buy with no down payment; a funding fee usually applies instead of monthly mortgage insurance",
          "USDA Rural Development: no-down-payment loans for eligible properties in designated rural areas — which include more of Florida than most buyers expect — with income limits by county",
          "Down payment assistance: state and local programs can layer on top of these; availability and terms change, so verify what is currently offered where you are buying"
        ]
      },
      {
        heading: "The real tradeoffs of putting less down",
        paragraphs: [
          "A smaller down payment means a larger loan, which means a larger monthly payment and more total interest over the life of the loan. Under 20 percent on a conventional loan, it also means PMI — a monthly cost that protects the lender, not you, though federal law provides for its removal once your equity reaches the required level. On FHA loans, mortgage insurance works differently and, depending on your down payment, can last the life of the loan, which is one reason buyers sometimes refinance out of FHA later.",
          "A larger down payment buys you a smaller payment, less interest, no or cheaper mortgage insurance, and instant equity that cushions you if values dip. What it costs you is liquidity — and in Florida, liquidity is not a luxury. A new roof after a storm, an insurance premium that jumps at renewal, a special assessment if you bought a condo: these arrive on their own schedule. A buyer who put every dollar into the down payment and kept no reserves is fragile in a way the monthly payment never shows.",
          "There is no universally right answer. A useful frame: decide first how much cash you need to keep — closing costs, moving, an emergency fund sized for Florida homeownership — and let the down payment be what remains, not the other way around."
        ]
      },
      {
        heading: "Down payment is not the same as cash to close",
        paragraphs: [
          "First-time buyers routinely conflate the down payment with the total cash they need. They are different numbers. On top of the down payment, you will pay closing costs — lender fees, title charges, Florida documentary stamp taxes, prepaid insurance and property taxes for the escrow account — and in Florida the insurance line deserves particular respect, since a full year of homeowners premium (plus flood insurance, if required) is typically collected at closing.",
          "Your Loan Estimate will show the full cash-to-close figure within three business days of applying, which is why applying early beats guessing. If your cash is thin, remember that gift funds from family are allowed under documented rules, and that seller credits toward closing costs can be negotiated into a Florida contract. TRACT arranges loans across all of these program families and can model the same purchase under each, so the comparison is concrete rather than conceptual."
        ]
      }
    ],
    faqs: [
      {
        question: "Is PMI wasted money?",
        answer:
          "PMI is a cost, but calling it wasted misses the arithmetic. It is the price of buying years earlier than saving 20 percent would allow. If home values and rents rise while you save, waiting has a cost too — often a larger one. The honest comparison is total cost of buying now with PMI versus renting while saving, and a rent-vs-buy calculator makes that comparison concrete."
      },
      {
        question: "How do I get rid of PMI once I have it?",
        answer:
          "For conventional loans, the federal Homeowners Protection Act gives you the right to request cancellation once your loan balance reaches the required equity threshold, and requires automatic termination at a further threshold, assuming you are current on payments. The CFPB explains the mechanics. FHA mortgage insurance follows different rules and may require refinancing to remove."
      },
      {
        question: "Can my whole down payment be a gift from my parents?",
        answer:
          "Often yes, depending on the program and property type. Gift funds are allowed under documented rules: the donor must be an acceptable source (typically family), sign a gift letter stating no repayment is expected, and the transfer must leave a paper trail. Program specifics vary, so tell your loan officer early if a gift is part of your plan."
      },
      {
        question: "Does a bigger down payment make my offer stronger in Florida?",
        answer:
          "Somewhat. Listing agents read a larger down payment as lower financing risk, and it can help if the appraisal comes in low, since you have more room to restructure the loan. But a verified preapproval, clean contingencies, and realistic dates usually matter more to a seller than the down payment percentage itself."
      }
    ],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is private mortgage insurance?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-private-mortgage-insurance-en-122/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Loan options: conventional, FHA, VA, and USDA loans",
        url: "https://www.consumerfinance.gov/owning-a-home/loan-options/"
      },
      {
        publisher: "Fannie Mae",
        title: "HomeReady mortgage",
        url: "https://singlefamily.fanniemae.com/originating-underwriting/mortgage-products/homeready-mortgage"
      },
      {
        publisher: "U.S. Department of Veterans Affairs",
        title: "VA home loans",
        url: "https://www.va.gov/housing-assistance/home-loans/"
      },
      {
        publisher: "USDA Rural Development",
        title: "Single Family Housing Guaranteed Loan Program",
        url: "https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-guaranteed-loan-program"
      }
    ],
    related: [
      { href: "/calculators/mortgage-payment", label: "Mortgage payment calculator" },
      { href: "/calculators/rent-vs-buy", label: "Rent vs. buy calculator" },
      { href: "/mortgage/fha", label: "FHA loans" },
      { href: "/mortgage/va", label: "VA loans" },
      { href: "/mortgage/usda", label: "USDA loans" },
      { href: "/resources/gift-funds-rules", label: "Gift funds rules" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "gift-funds-rules",
    category: "first-time",
    title: "Mortgage Gift Funds: Rules, Letters, and Documentation",
    description:
      "Family gifts can fund your down payment — if you follow the rules. Who can gift, what the gift letter must say, and why seasoning and paper trails matter.",
    h1: "Gift funds for your down payment: the rules, the letter, and the paper trail",
    answerSummary:
      "Most loan programs allow down payment gifts from family members and certain other close relationships, but the money must be documented: a signed gift letter stating no repayment is expected, plus a paper trail showing the funds leaving the donor's account and arriving in yours. Cash under the mattress does not count. Handled early and by the book, gifts are routine; handled casually, they are one of the most common causes of underwriting delays.",
    sections: [
      {
        heading: "Who is allowed to give you money",
        paragraphs: [
          "Lenders care where your down payment comes from because borrowed money disguised as a gift changes your real debt load. So programs define acceptable donors. For conventional loans, Fannie Mae's Selling Guide defines the acceptable donor list around family — spouse, children, other relatives by blood, marriage, adoption, or legal guardianship — along with certain close relationships like a domestic partner or fiancé. FHA, VA, and USDA each maintain their own donor rules, which broadly rhyme with this but differ in details.",
          "Two categories are firmly excluded everywhere: anyone with an interest in the transaction (the seller, the agent, the builder — except through separately regulated interested-party contribution rules) and anyone expecting repayment. A gift that is secretly a loan is misrepresentation, and it is the kind that surfaces, because underwriters are trained to look for it."
        ]
      },
      {
        heading: "The gift letter: what it must actually say",
        paragraphs: [
          "Every program requires a gift letter, and its content is standard. The letter is short but load-bearing — it is the donor's written statement, and signing one that is false is fraud. A complete letter includes:"
        ],
        bullets: [
          "The donor's name, address, phone number, and relationship to you",
          "The dollar amount of the gift",
          "The address of the property being purchased, once known",
          "An explicit statement that no repayment is expected or required",
          "The donor's signature and, for most programs, yours as well"
        ]
      },
      {
        heading: "Seasoning and the paper trail: why the money's history matters",
        paragraphs: [
          "Underwriters verify assets by reading your recent bank statements — typically the last two months. Money that has sat in your account for that full window is considered seasoned: its history predates the statements, so no further sourcing is required. Money that appears inside the window is a large deposit, and every large deposit must be explained and documented.",
          "This is where gift funds get procedurally interesting. A gift is by definition a recent large deposit, so it must be fully sourced: the gift letter, plus evidence of the transfer — the donor's withdrawal, the check or wire, and your deposit. Many programs also allow the gift to be sent directly to the closing agent at settlement, which can be cleaner than routing it through your account.",
          "The practical consequences: first, if family plans to help, either move the money early enough to season it or keep it in the donor's account until it can be transferred with clean documentation — the worst pattern is money hopping between accounts, because each hop needs its own paperwork. Second, never take a gift in physical cash. Cash has no source that underwriting can verify, and depositing it right before applying creates a deposit that cannot be documented. Third, the donor should expect to show their own statement; some donors bristle at this, so warn them before underwriting asks."
        ]
      },
      {
        heading: "Taxes: a donor question, not a buyer question",
        paragraphs: [
          "Buyers often worry the gift will be taxed as their income. It will not — gifts are not income to the recipient under federal tax law. Gift tax, to the extent it applies, is the donor's concern, and for most family gifts it amounts to a filing question rather than a tax bill: gifts above the annual exclusion amount require the donor to file a gift tax return, but a lifetime exemption typically absorbs the tax itself. Both figures are adjusted over time, so check the current amounts on the IRS gift tax FAQ or with a tax professional rather than relying on remembered numbers.",
          "The mortgage process and the tax rules are separate systems: the gift letter satisfies the lender, not the IRS, and an IRS filing does not satisfy the lender. Donors giving large amounts should talk to their tax advisor; buyers should tell their loan officer a gift is coming as early as possible — ideally at preapproval. TRACT arranges loans across conventional and government programs, and knowing a gift is in the file from day one lets the documentation be staged before an underwriter ever asks."
        ]
      }
    ],
    faqs: [
      {
        question: "Can gift funds cover my entire down payment and closing costs?",
        answer:
          "Frequently yes, but it depends on the program, the property type, and sometimes the size of your down payment. Conventional rules can require a minimum contribution from your own funds in certain scenarios, such as some two- to four-unit or second-home purchases, while gifts covering everything are common on single-family primary residences. Confirm the rule for your specific program before you plan around it."
      },
      {
        question: "What if I already deposited a cash gift into my account?",
        answer:
          "Talk to your loan officer before doing anything else. Depending on timing, the options are usually to document the transfer as well as possible, wait until the deposit seasons out of the statement window, or in the worst case exclude those funds from the file and qualify without them. What does not work is hoping the underwriter will not notice — large deposits are specifically what they review statements for."
      },
      {
        question: "Does the donor have to be a U.S. citizen or use a U.S. bank?",
        answer:
          "Donors abroad are common in Florida and gifts from them are generally workable, but international transfers need extra documentation and time — evidence of the sending account, the wire trail, and currency conversion records. Start that process early, because chasing paperwork across time zones during your loan approval period is a self-inflicted delay."
      },
      {
        question: "Is a loan from family ever acceptable instead of a gift?",
        answer:
          "Not disguised as a gift — that is misrepresentation. Genuine borrowed funds are treated as debt: disclosed, documented, and counted in your debt-to-income ratio, and programs restrict which borrowed sources may fund a down payment at all. If family money comes with repayment expectations, tell your loan officer so it can be structured honestly."
      }
    ],
    sources: [
      {
        publisher: "Fannie Mae",
        title: "Selling Guide B3-4.3-04: Personal Gifts",
        url: "https://selling-guide.fanniemae.com/sel/b3-4.3-04/personal-gifts"
      },
      {
        publisher: "Internal Revenue Service",
        title: "Frequently asked questions on gift taxes",
        url: "https://www.irs.gov/businesses/small-businesses-self-employed/frequently-asked-questions-on-gift-taxes"
      }
    ],
    related: [
      { href: "/resources/down-payment-how-much", label: "How much down payment do you need?" },
      { href: "/resources/underwriting-conditions", label: "Underwriting conditions explained" },
      { href: "/mortgage/first-time-home-buyers", label: "First-time home buyer programs" },
      { href: "/calculators/closing-cost", label: "Closing cost calculator" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "closing-timeline-florida",
    category: "first-time",
    title: "Florida Closing Timeline: Contract to Keys",
    description:
      "What actually happens between signing a Florida purchase contract and getting keys — the sequence, the deadlines that bite, and what most commonly causes delays.",
    h1: "The Florida closing timeline: what happens between contract and keys",
    answerSummary:
      "A financed Florida purchase typically runs about thirty to forty-five days from signed contract to closing, moving through loan application, inspections, insurance binding, appraisal, title work, underwriting, the Closing Disclosure with its mandatory three-business-day review window, and finally the closing itself. The most common delays are insurance placement on older roofs, condo association reviews, appraisal turnaround, and buyers whose finances change mid-process. Most delays are preventable with early action.",
    sections: [
      {
        heading: "Week one: application, escrow, and inspections start immediately",
        paragraphs: [
          "The clock starts the day the last party signs. Florida's standard Florida Realtors/Florida Bar contract forms set nearly every deadline as a count of days from that effective date, so the first week is dense. Your earnest money deposit is due to the escrow agent within the contracted window. Your loan application must be submitted within the contracted financing period start — and once you apply, federal rules require the lender to deliver your Loan Estimate within three business days.",
          "The inspection period usually runs concurrently and is short. Schedule the general inspection immediately, and in Florida add the insurance-driven inspections: a wind mitigation inspection, which can reduce your homeowners premium, and a four-point inspection (roof, electrical, plumbing, HVAC), which many insurers require on older homes before they will issue a policy at all."
        ]
      },
      {
        heading: "Weeks two and three: insurance, appraisal, title, and the condo question",
        paragraphs: [
          "Start shopping homeowners insurance the day you go under contract, not the week before closing. This is the single most Florida-specific piece of advice in the entire process. Insurers scrutinize roof age and condition, a required flood policy adds a second placement if the home sits in a FEMA special flood hazard area, and during hurricane season carriers suspend binding new policies whenever a named storm approaches — a moratorium that can freeze your closing for days through no fault of yours.",
          "Meanwhile the lender orders the appraisal, an independent opinion of the property's value that the loan amount will be measured against. The title agent or attorney searches the public records, clears liens and open permits, and prepares the title commitment. If you are buying a condo, the association review runs in parallel: budget, reserves, insurance, litigation, and owner-occupancy questions that the lender must resolve before approving the loan. Condo reviews are a common source of added time, so treat a condo contract's dates more generously.",
          "Somewhere in this stretch, underwriting issues a conditional approval — an approval subject to a list of conditions. Clearing them fast is mostly a matter of responding to document requests the same day they arrive."
        ]
      },
      {
        heading: "The final week: Closing Disclosure, the three-day rule, and the walkthrough",
        paragraphs: [
          "Once underwriting clears your conditions and the property file is complete, the lender issues the Closing Disclosure — the final five-page statement of your loan terms and cash to close. Federal law requires you to receive it at least three business days before closing, and certain changes after that (a changed APR beyond tolerance, a changed loan product, or an added prepayment penalty) restart the three-day window. This rule exists so the final numbers cannot be sprung on you at the table, and it is why last-minute changes move closing dates.",
          "Compare the Closing Disclosure to your most recent Loan Estimate line by line, and question anything that moved. Wire your cash to close only using instructions verbally confirmed with the title company at a number you looked up independently — wire fraud targeting Florida closings is real and unrecoverable. The day of or before closing, do the final walkthrough to confirm the property's condition and that any negotiated repairs were completed. Closing itself is signatures, funding, and recording; in Florida it is customarily conducted by a title company or attorney, and once the deed records, the keys are yours."
        ]
      },
      {
        heading: "What actually causes delays — and what prevents them",
        paragraphs: [
          "Almost every delayed Florida closing traces to a handful of causes, and most are preventable by acting in week one rather than week four:"
        ],
        bullets: [
          "Insurance placed late: old roofs, four-point findings, flood zone surprises, or a hurricane binding moratorium — shop coverage the first week",
          "Condo association reviews or estoppel letters that arrive slowly — order them immediately on condo deals",
          "Appraisal issues: slow turnaround in busy markets, or a value below contract price that forces renegotiation",
          "Title defects: open permits, unsatisfied liens, or estate issues on the seller's side",
          "Borrower self-sabotage: new debts, job changes, moved money, or unanswered document requests during underwriting",
          "Closing Disclosure changes that legally restart the three-business-day clock"
        ]
      }
    ],
    faqs: [
      {
        question: "Can a Florida closing happen faster than thirty days?",
        answer:
          "Yes, when everything cooperates — a responsive buyer with a complete file, a fast appraisal, clean title, and quick insurance placement. Cash closings routinely run faster because the entire lender track disappears. But contracted dates should reflect realistic timelines, because missing a closing date can put your deposit at risk depending on the contract's terms."
      },
      {
        question: "What happens if my financing falls through before closing?",
        answer:
          "It depends on your contract's financing terms and dates. Florida's standard contract forms include a financing contingency that, if properly invoked within its period, lets you cancel and recover your deposit. Let the period lapse without terminating, and you may be obligated to close or forfeit the deposit. Track the date and talk to your agent well before it arrives."
      },
      {
        question: "Why does everyone say to start insurance shopping immediately?",
        answer:
          "Because in Florida, insurance is the step most likely to be slower and harder than expected. Roof condition can shrink your options, a flood policy may be separately required, and a named storm entering the forecast can suspend new policy binding statewide until it passes. The lender cannot close without proof of coverage, so late insurance means a late closing."
      },
      {
        question: "Do I need an attorney to close in Florida?",
        answer:
          "Florida does not require one; closings are customarily handled by title companies or attorneys acting as settlement agents, and the contract specifies who chooses. An attorney is worth considering for unusual situations — estates, foreign sellers, title complications — and buyers are always free to hire one to review documents."
      }
    ],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Buying a House: Get ready to close",
        url: "https://www.consumerfinance.gov/owning-a-home/process/close/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is a Closing Disclosure?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-closing-disclosure-en-1983/"
      },
      {
        publisher: "eCFR",
        title: "12 CFR 1026.19 — TILA-RESPA disclosure timing requirements",
        url: "https://www.ecfr.gov/current/title-12/chapter-X/part-1026/subpart-C/section-1026.19"
      },
      {
        publisher: "FloodSmart / National Flood Insurance Program",
        title: "FloodSmart.gov — the National Flood Insurance Program",
        url: "https://www.floodsmart.gov/"
      }
    ],
    related: [
      {
        href: "/resources/closing-disclosure-explained",
        label: "The Closing Disclosure explained"
      },
      { href: "/resources/earnest-money-florida", label: "Earnest money in Florida" },
      { href: "/resources/home-appraisal-explained", label: "How appraisals work" },
      { href: "/calculators/closing-cost", label: "Closing cost calculator" },
      { href: "/mortgage/condo", label: "Condo loans" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "loan-estimate-explained",
    category: "first-time",
    title: "How to Read Your Loan Estimate, Line by Line",
    description:
      "The Loan Estimate is three pages that tell you everything about your mortgage offer — if you know where to look. Which numbers can change, and which cannot.",
    h1: "How to actually read a Loan Estimate",
    answerSummary:
      "A Loan Estimate is the standardized three-page form every lender must send within three business days of your mortgage application. Page one shows the loan terms and cash to close, page two itemizes costs, and page three carries the comparison figures built for shopping between lenders. Federal tolerance rules control which numbers can change before closing: lender fees are locked, some third-party charges can rise within a capped tolerance, and items like insurance can change freely.",
    sections: [
      {
        heading: "What the Loan Estimate is and when you get it",
        paragraphs: [
          "The Loan Estimate exists because mortgage offers used to be incomparable on purpose. Since the TILA-RESPA integrated disclosure rules took effect, every lender must present its offer on the identical three-page federal form, delivered within three business days of receiving your application. Same layout, same labels, same math — which means two Loan Estimates can be laid side by side and read against each other line for line.",
          "Receiving one commits you to nothing. It is a disclosure, not a contract, and lenders cannot charge you anything beyond a reasonable credit report fee before you receive it and tell them you intend to proceed. That design is deliberate: the form is meant to be collected from multiple lenders and compared. Not collecting more than one is leaving the entire point of the document unused."
        ]
      },
      {
        heading: "Page one: the loan itself",
        paragraphs: [
          "Page one is the summary that most decisions should be made from. The Loan Terms table shows the loan amount, the interest rate, and the monthly principal and interest — and, critically, a yes/no column stating whether each can increase after closing. On a fixed-rate loan those answers should be no; on an adjustable-rate loan this table is where the adjustment exposure is disclosed. The same table states whether the loan carries a prepayment penalty or a balloon payment. Read those two lines every time; they are where unpleasant loan features are legally required to announce themselves.",
          "The Projected Payments table adds escrow — the monthly collection for property taxes and insurance — to show the actual payment you will write each month, and shows how it changes over time. In Florida, be skeptical of the estimated escrow on a purchase: it may be seeded from the seller's current tax bill, and property taxes reset on sale, so your real second-year payment can be meaningfully higher than the form's first-year figure. Costs at Closing, at the bottom of page one, previews the two numbers everyone flips to: total closing costs and estimated cash to close.",
          "One line deserves special attention: the rate lock indicator. If the rate is not locked, everything priced off it can move until it is. Ask the lender directly what the lock status and expiration are."
        ]
      },
      {
        heading: "Pages two and three: where the costs live and how to compare lenders",
        paragraphs: [
          "Page two itemizes closing costs in lettered sections, and the lettering encodes who controls each cost. Section A is the lender's own origination charges, including any discount points. Section B is services you cannot shop for, like the appraisal. Section C is services you can shop for, such as title work — with the lender's provider list attached. Sections E through G cover government recording charges and taxes (a real line item in Florida, where documentary stamp and intangible taxes apply), prepaids, and the initial escrow deposit. Section H catches the rest, and Section J totals it. Lender credits, if any, appear as a negative number reducing your costs.",
          "When comparing lenders, compare Section A against Section A at the same rate and lock period — that is the cleanest read of what each lender itself charges. Third-party and government costs will be roughly similar everywhere, and prepaid items are your own taxes and insurance no matter who lends. Page three's comparison box helps too: the five-year cost figure, the APR, and total interest percentage put rate-versus-fees tradeoffs on a common scale.",
          "The tolerance rules are what give the form teeth. Under the federal rules, the lender's own charges in Section A and transfer taxes cannot increase at closing at all, absent a legitimate changed circumstance. Charges in the capped category — recording fees, and services you could shop for but chose from the lender's list — can rise in aggregate only within a limited tolerance. Items like prepaid interest, homeowners insurance, and services where you chose your own provider can change without limit, because the lender does not control them. If a locked number rises anyway, the lender generally owes you a refund of the excess."
        ]
      },
      {
        heading: "Reading it like an underwriter: a short checklist",
        paragraphs: [
          "Ten minutes with each Loan Estimate, in this order, will catch nearly everything that matters:"
        ],
        bullets: [
          "Confirm loan amount, rate, product type, and term match what you were quoted",
          "Check the can-this-increase column, prepayment penalty, and balloon payment lines",
          "Check whether the rate is locked and when the lock expires",
          "Read Section A as the lender's true price; note any discount points you did not ask for",
          "Sanity-check the escrow estimate against a realistic post-sale Florida tax bill and a real insurance quote",
          "Use page three's five-year cost and APR to compare offers with different rate/fee mixes",
          "Keep every Loan Estimate you receive — the final Closing Disclosure must be compared against it"
        ]
      }
    ],
    faqs: [
      {
        question: "Does getting a Loan Estimate obligate me to that lender?",
        answer:
          "No. The Loan Estimate is a disclosure designed for shopping, and until you tell the lender you intend to proceed, the only fee you can generally be charged is a reasonable credit report fee. You can collect estimates from several lenders and walk away from any or all of them."
      },
      {
        question: "Why is the APR different from my interest rate?",
        answer:
          "The interest rate prices the loan balance; the APR expresses the total cost of credit — rate plus certain fees and points — as a yearly figure. A loan with a lower rate but heavy upfront fees can carry a higher APR than a loan with a higher rate and minimal fees. That is exactly the tradeoff the APR exists to surface, which makes it useful for comparing offers, though it should be read alongside how long you expect to keep the loan."
      },
      {
        question: "What counts as a changed circumstance that lets numbers move?",
        answer:
          "Legitimate examples include an appraisal revealing different property facts, a change you request yourself (a different loan amount or product), a rate lock after the estimate was issued, or information in your application proving inaccurate. When one occurs, the lender issues a revised Loan Estimate and the tolerance baselines reset for the affected charges. Revisions without an identifiable trigger are worth questioning."
      },
      {
        question: "My cash to close looks higher than the down payment I planned. Why?",
        answer:
          "Cash to close bundles the down payment with closing costs, prepaid insurance and interest, and the initial escrow deposit — in Florida, that typically includes a full year of homeowners premium paid up front, plus several months of taxes and insurance into escrow. Seller credits and lender credits reduce it; the calculating cash to close table on page two shows exactly how the number is built."
      }
    ],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Loan Estimate Explainer",
        url: "https://www.consumerfinance.gov/owning-a-home/loan-estimate/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is a Loan Estimate?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-loan-estimate-en-1995/"
      },
      {
        publisher: "eCFR",
        title: "12 CFR 1026.19 — TILA-RESPA disclosure timing requirements",
        url: "https://www.ecfr.gov/current/title-12/chapter-X/part-1026/subpart-C/section-1026.19"
      }
    ],
    related: [
      {
        href: "/resources/closing-disclosure-explained",
        label: "The Closing Disclosure explained"
      },
      {
        href: "/resources/preapproval-vs-prequalification",
        label: "Preapproval vs. prequalification"
      },
      { href: "/calculators/rate-impact", label: "Rate impact calculator" },
      { href: "/calculators/closing-cost", label: "Closing cost calculator" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "closing-disclosure-explained",
    category: "first-time",
    title: "Closing Disclosure Explained: The 3-Day Rule",
    description:
      "The Closing Disclosure is your mortgage's final answer. What the five pages say, how the three-business-day rule protects you, and how to compare it to your LE.",
    h1: "The Closing Disclosure: your loan's final numbers, and the three days you get to check them",
    answerSummary:
      "The Closing Disclosure is the five-page federal form stating your mortgage's final terms and costs, and the lender must ensure you receive it at least three business days before closing. Those three days exist for one purpose: comparing it against your Loan Estimate and challenging anything that moved improperly. Certain changes — an APR beyond tolerance, a different loan product, or an added prepayment penalty — legally restart the clock.",
    sections: [
      {
        heading: "What the Closing Disclosure is",
        paragraphs: [
          "Everything before this form was an estimate. The Closing Disclosure is the final accounting: the loan amount, rate, and payment you are actually getting, every closing cost with its final figure, exactly what you owe at the table, and a settlement summary of the whole transaction between you and the seller. It replaced the old HUD-1 settlement statement for most mortgages and was designed to mirror the Loan Estimate page for page, so the two documents can be compared without translation.",
          "It is issued when underwriting is essentially done and the closing figures are final. Because federal law requires you to receive it at least three business days before consummation, its issuance also effectively sets your earliest possible closing date — which is why lenders, agents, and title companies all push to get the CD out on time when a contract's closing date is near."
        ]
      },
      {
        heading: "The three-business-day rule, and what restarts it",
        paragraphs: [
          "The rule is simple: three business days must pass between your receipt of the Closing Disclosure and your closing. The purpose is equally simple. Before this rule, buyers often met their final numbers for the first time at the closing table, with movers scheduled and no realistic ability to push back. The waiting period moves that discovery to a moment when you can still act.",
          "Not every subsequent change restarts the clock — most corrections just require an updated CD you receive at or before closing. Three do restart it, and they are the serious ones: the APR moving beyond the regulation's tolerance, the loan product itself changing (say, fixed to adjustable), or a prepayment penalty being added. If one of those happens two days before your scheduled closing, the closing moves. That is not the process failing; that is the process working.",
          "Use the days. Read every page. If something looks wrong, raise it immediately with your loan officer and the settlement agent — small errors (a misspelled name, a wrong escrow figure) are far easier to fix before closing than after the loan funds and the documents record."
        ]
      },
      {
        heading: "Comparing the CD to your Loan Estimate",
        paragraphs: [
          "The comparison is the whole exercise, and the forms are built for it. Put your most recent Loan Estimate next to the CD and work through the matching sections:"
        ],
        bullets: [
          "Page one: loan amount, rate, monthly principal and interest, and the can-this-increase answers should match the LE, or you should know exactly why not",
          "Prepayment penalty and balloon payment lines: still no, unless you knowingly agreed otherwise",
          "Section A (origination charges): zero-tolerance territory — these should not have increased without a documented changed circumstance",
          "Sections B and C: check the capped-tolerance category for aggregate increases beyond the allowed limit",
          "Page three, calculating cash to close: this table explicitly shows each LE figure, the final figure, and whether it changed — read the yes rows",
          "Seller credits and lender credits: confirm every negotiated credit actually appears",
          "Page two escrow and prepaids: verify the insurance premium matches your actual policy and the tax figures are plausible for a post-sale Florida assessment"
        ]
      },
      {
        heading: "If a number moved improperly",
        paragraphs: [
          "The tolerance rules that governed your Loan Estimate are enforced at the Closing Disclosure. Lender origination charges and transfer taxes generally cannot exceed the estimate at all; the capped category cannot exceed it beyond the aggregate tolerance. When a charge lands beyond its tolerance without a legitimate changed circumstance, the lender owes you the difference — typically as a credit at closing or a refund shortly after. Politely asking why did this change, citing the specific line matters, because the settlement agent and lender can correct figures before closing far more easily than after.",
          "Also verify the closing logistics the CD implies: your cash to close must arrive as a wire or certified funds, and wire instructions should only ever be trusted after verbally confirming them with the title company at a phone number you found independently — not one from an email. Fraudulent last-minute changed wire instructions remain one of the most damaging scams in real estate, and Florida's high transaction volume makes it a favorite hunting ground. TRACT arranges loans rather than making them, but walking clients through the CD-to-LE comparison before closing day is part of the job; three quiet days with the form beats thirty confused minutes at the table."
        ]
      }
    ],
    faqs: [
      {
        question: "Can I waive the three-business-day waiting period?",
        answer:
          "Only in a narrow, genuine emergency. The regulation permits waiver for a bona fide personal financial emergency — the classic example is a foreclosure sale that will occur before the period ends — and it requires your own written, non-form explanation. Routine scheduling pressure, expiring rate locks, and movers on the calendar do not qualify, and lenders almost never accept waivers in ordinary purchases."
      },
      {
        question: "What if I find an error on the Closing Disclosure at the table?",
        answer:
          "Raise it before signing. Numeric errors can often be corrected on the spot with a revised CD; clerical errors can be fixed post-closing with a corrected disclosure. If the error is one of the three that trigger a new waiting period — APR beyond tolerance, changed product, added prepayment penalty — closing must be rescheduled. Signing with a known material error and hoping is the one wrong answer."
      },
      {
        question: "Does the seller see my Closing Disclosure?",
        answer:
          "Not the loan side. Sellers receive their own disclosure showing the transaction summary from their side, prepared by the settlement agent. Your loan terms, costs, and financial details are not part of the seller's document."
      },
      {
        question: "Why did my cash to close change from the Loan Estimate?",
        answer:
          "Some movement is normal and legitimate: final prorations of property taxes between you and the seller, per-diem prepaid interest that depends on your actual closing date, the real insurance premium replacing an estimate, and any negotiated credits. The calculating cash to close table on page three itemizes precisely which components moved. What should not move are zero-tolerance charges — those are the lines to challenge."
      }
    ],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Closing Disclosure Explainer",
        url: "https://www.consumerfinance.gov/owning-a-home/closing-disclosure/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is a Closing Disclosure?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-closing-disclosure-en-1983/"
      },
      {
        publisher: "eCFR",
        title: "12 CFR 1026.19 — TILA-RESPA disclosure timing requirements",
        url: "https://www.ecfr.gov/current/title-12/chapter-X/part-1026/subpart-C/section-1026.19"
      }
    ],
    related: [
      { href: "/resources/loan-estimate-explained", label: "How to read a Loan Estimate" },
      { href: "/resources/closing-timeline-florida", label: "Florida closing timeline" },
      { href: "/calculators/closing-cost", label: "Closing cost calculator" },
      { href: "/contact", label: "Ask us about your closing numbers" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "earnest-money-florida",
    category: "first-time",
    title: "Earnest Money in Florida: Who Holds It, When It's at Risk",
    description:
      "Your earnest money deposit shows a Florida seller you're serious — and it's real money at real risk. Who holds it, how escrow works, and how deposits get lost.",
    h1: "Earnest money in Florida: what it is, who holds it, and when you can lose it",
    answerSummary:
      "Earnest money is a good-faith deposit a buyer puts into escrow shortly after a Florida contract is signed, showing the seller the offer is backed by real money. A neutral escrow agent — usually a title company, attorney, or real estate broker — holds it, and Florida law strictly regulates brokers who do. At closing it credits toward your purchase; if you miss a contractual deadline or walk away outside your contingencies, the seller may claim it.",
    sections: [
      {
        heading: "What earnest money is and what it is not",
        paragraphs: [
          "A signed purchase contract obligates a seller to take the home off the market for weeks on the buyer's word. Earnest money is what makes that word expensive to break: a deposit, made days after the effective date, that the buyer stands to lose by defaulting. It is not an extra fee — at closing the full deposit credits toward your down payment and closing costs — and it is not the down payment itself, just the earliest piece of it, posted as a performance bond.",
          "The amount is negotiated, not fixed by any law or rule. Local custom in Florida commonly runs in the low single-digit percents of the purchase price, but competitive situations push it higher because a larger deposit signals commitment. Some contracts also stage it: an initial deposit at signing and an additional deposit after the inspection period. The right amount is a strategy question for you and your agent; the right protection is a contract whose contingencies you understand."
        ]
      },
      {
        heading: "Who holds the money: escrow, and Florida's rules about it",
        paragraphs: [
          "The deposit never goes to the seller. It goes to a neutral third party — the escrow agent named in the contract, typically a title company, a closing attorney, or a real estate broker — who holds it until the contract tells them what to do with it. This neutrality is the point: neither side can touch the money unilaterally while the deal is alive.",
          "When a Florida real estate broker holds the deposit, state law regulates the arrangement heavily. Chapter 475 of the Florida Statutes requires brokers to place escrow funds immediately upon receipt into a proper escrow account, and failing to account for or deliver escrowed funds is grounds for discipline against the broker's license. When the parties dispute who gets the deposit, a broker holding it must follow statutory settlement procedures — which can include requesting a disbursement order from the Florida Real Estate Commission, mediation, arbitration, or interpleading the funds into court — rather than simply picking a side.",
          "Practical hygiene for buyers: deliver the deposit by wire or check to the escrow agent named in the contract, on time, and keep the receipt. Verify wire instructions by phone with the escrow agent at an independently confirmed number — deposit wires are targeted by the same fraud that targets closing funds. And never make any deposit payable to the seller personally."
        ]
      },
      {
        heading: "When your deposit is protected — and when it is at risk",
        paragraphs: [
          "Whether you can walk away with your deposit depends entirely on the contract's contingencies and deadlines, not on fairness or good intentions. Under Florida's widely used contract forms, the protective structure generally looks like this:"
        ],
        bullets: [
          "Inspection period: the AS-IS Florida Realtors/Florida Bar contract typically lets the buyer cancel for any reason within the inspection period and recover the deposit — the broadest protection you get, and it is brief",
          "Financing contingency: if you apply diligently and cannot obtain loan approval, terminating within the financing period preserves the deposit; letting the period lapse silently converts financing failure into buyer default",
          "Appraisal: protection depends on how your financing or appraisal terms are written — a low appraisal is not automatically an exit",
          "Title and other named contingencies: defects the seller cannot cure within the contract's terms typically permit cancellation with the deposit returned",
          "After contingencies expire: walking away for cold feet, a better house, or an unfavorable market shift is default, and the contract typically names the deposit as the seller's remedy",
          "Missed performance: failing to deliver the deposit on time, blowing the closing date without an authorized extension, or failing to make the loan application within the contracted window can each place the deposit at risk"
        ]
      },
      {
        heading: "If a dispute happens",
        paragraphs: [
          "Deposit disputes are usually about deadlines: a cancellation notice sent a day late, a financing termination that cited the wrong clause, an extension both agents discussed but nobody signed. When both parties claim the money, the escrow agent freezes: brokers follow the Chapter 475 procedures, and title companies or attorneys follow the contract's dispute terms, often ending in mediation as the contract's first required step.",
          "The uncomfortable truth is that prevention is procedural. Calendar every deadline the day you sign, deliver every notice in writing through the contractually specified channel, and get every extension signed — not promised. Buyers rarely lose deposits to dramatic events; they lose them to dates. Your agent manages this calendar, and on the financing side, a responsive loan file is deposit protection: TRACT arranges loans through wholesale lenders, and keeping your approval moving on schedule is part of what keeps your financing contingency from ever becoming the problem."
        ]
      }
    ],
    faqs: [
      {
        question: "Is earnest money legally required in Florida?",
        answer:
          "No law requires it, but as a practical matter a Florida offer without a deposit is not competitive — sellers read the deposit as the measure of your seriousness. The amount and timing are whatever the contract says, which makes them negotiable before signing and binding after."
      },
      {
        question: "Do I get my deposit back if the inspection finds problems?",
        answer:
          "Under the AS-IS Florida Realtors/Florida Bar contract, cancellation within the inspection period returns the deposit regardless of the reason, so inspection findings are covered. Under other contract versions, repair provisions govern instead. The protection lives in the specific form and dates you signed, so know which contract you are on before assuming."
      },
      {
        question: "Can the seller just keep my deposit if we disagree?",
        answer:
          "No. The escrow agent cannot release disputed funds to either side unilaterally. A broker holding the deposit must follow the statutory dispute procedures under Florida law, and other escrow agents follow the contract's dispute resolution terms. It may take time, but the money cannot simply be taken."
      },
      {
        question: "Does my earnest money earn interest while in escrow?",
        answer:
          "Only if the contract says so. Standard Florida contract forms make interest-bearing escrow an option the parties must affirmatively choose, and for typical deposit sizes over a thirty-to-forty-five-day escrow, the interest is negligible. Most transactions use non-interest-bearing escrow for simplicity."
      }
    ],
    sources: [
      {
        publisher: "Florida Senate",
        title: "Florida Statutes § 475.25 — broker escrow and discipline provisions",
        url: "https://www.flsenate.gov/Laws/Statutes/2024/475.25"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Buying a House: Get ready to close",
        url: "https://www.consumerfinance.gov/owning-a-home/process/close/"
      }
    ],
    related: [
      { href: "/resources/closing-timeline-florida", label: "Florida closing timeline" },
      {
        href: "/resources/preapproval-vs-prequalification",
        label: "Preapproval vs. prequalification"
      },
      { href: "/mortgage/purchase", label: "Purchase loans" },
      { href: "/calculators/closing-cost", label: "Closing cost calculator" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "home-appraisal-explained",
    category: "first-time",
    title: "Home Appraisals: Process, Gaps, and Low Values",
    description:
      "What appraisers actually do, why the lender orders one, what an appraisal gap means for your contract, and your real options when the value comes in low.",
    h1: "The home appraisal: what appraisers do, and what happens when the number comes in low",
    answerSummary:
      "An appraisal is an independent, licensed professional's written opinion of a home's market value, ordered through the lender because the loan is sized against the property's value, not its price. Most appraisals support the contract price and pass quietly. When one comes in low, the loan gets rebuilt around the smaller value, and the gap becomes a negotiation: renegotiate the price, bring extra cash, split the difference, challenge the report, or exit under the contract's terms.",
    sections: [
      {
        heading: "What the appraiser actually does",
        paragraphs: [
          "An appraisal is not an inspection, and the two are constantly confused. The inspector works for you and hunts defects; the appraiser produces an independent opinion of market value on which the lender will size its loan. The appraiser typically visits the property, measures and photographs it, notes condition, quality, and anything unusual, then builds the valuation — most commonly through the sales comparison approach: recent sales of similar nearby homes, adjusted line by line for differences in size, condition, features, and location.",
          "Independence is structural, not aspirational. Post-2008 rules put a firewall between loan production and valuation: lenders order appraisals through channels designed to prevent anyone with a stake in the deal from pressuring the appraiser, and neither the buyer, the seller, nor the loan officer selects who performs it. You pay for the appraisal, and under federal rules you are entitled to a copy of it promptly, but it is prepared for the lender. Fannie Mae's appraiser requirements — a signed, complete report accurately reflecting market value, condition, and marketability — describe what the resulting document must do."
        ]
      },
      {
        heading: "Why the lender cares so much",
        paragraphs: [
          "The property is the loan's collateral. If the borrower defaults, the home is what stands behind the debt — so the lender lends against the lesser of the price and the appraised value, never against enthusiasm. Every key ratio in your approval, starting with loan-to-value, is computed from that appraised value, and LTV drives whether mortgage insurance is required and how the loan is priced.",
          "This is worth internalizing as a buyer, because it reframes the appraisal from an obstacle into a service you happen to be paying for anyway: it is the one professional in the transaction whose entire job is to check, with evidence, whether the price you agreed to is defensible. In a fast-rising market, appraisals lag the frenzy and gaps appear; in a cooling one, the appraisal is sometimes the first honest signal a buyer receives."
        ]
      },
      {
        heading: "When the value comes in low: the appraisal gap",
        paragraphs: [
          "Suppose the contract price exceeds the appraised value. The lender now sizes the loan from the appraised value, which leaves a gap between the financing structure you planned and the one available. Nothing about the contract has changed yet — what happens next is negotiation, and your leverage depends on what your contract says and how the market feels that month. The realistic menu:"
        ],
        bullets: [
          "Renegotiate: the seller drops the price to the appraised value — common in balanced or cooling markets, since the next financed buyer's appraisal will likely say the same thing",
          "Bring cash: you cover the gap out of pocket, keeping the deal at the contract price with a larger effective down payment",
          "Split it: a negotiated price reduction plus some buyer cash meets in the middle — the most common resolved outcome",
          "Challenge the value: a reconsideration of value through the lender, citing specific factual errors or overlooked comparable sales; success is possible but not the norm, so treat it as a long shot with a deadline",
          "Restructure the loan: depending on your program and cash, adjusting the down payment split or accepting revised mortgage insurance terms can absorb part of the gap",
          "Exit: if your contract's financing or appraisal terms permit termination under these facts and the deadlines have not passed, you can walk with your deposit — verify the clause and the dates before relying on this"
        ]
      },
      {
        heading: "Florida specifics and practical advice",
        paragraphs: [
          "Florida adds a few wrinkles. Condo appraisals depend on recent sales within or near the same project, and buildings with unusual features or few recent sales produce noisier values. Storm-damaged or heavily renovated homes may require the appraiser to revisit and confirm completed repairs before closing, adding time. Coastal and flood-zone properties involve site factors that an appraiser must reflect. None of this is exotic — but each is a reason appraisal timelines deserve slack in a Florida contract.",
          "Practically: schedule the appraisal early in the loan period so a low value surfaces while you still have contractual room to respond; do not waive appraisal protections casually just to win a bidding war unless you truly have the cash to cover a gap; and read the report when you receive your copy — appraisers occasionally miss a renovation or use a stale comparable, and factual errors are the strongest basis for reconsideration. TRACT arranges loans and cannot influence any appraisal's outcome — independence rules exist precisely so nobody can — but structuring your approval with a plan for gap scenarios costs nothing and occasionally saves a contract."
        ]
      }
    ],
    faqs: [
      {
        question: "Who pays for the appraisal, and can I choose the appraiser?",
        answer:
          "The buyer typically pays as part of loan costs, and no — neither you, the seller, nor the loan officer selects the appraiser. Federal independence rules require the lender to order the appraisal through channels insulated from the transaction's participants. You are, however, entitled to a copy of the report promptly after it is completed."
      },
      {
        question: "What if the appraisal comes in higher than my contract price?",
        answer:
          "Congratulations — you keep it. The loan is based on the lesser of price and value, so a high appraisal does not change your loan, and the seller has no claim to renegotiate upward. It simply means you are buying with more day-one equity than your down payment alone provided. The seller never sees your appraisal unless you choose to share it."
      },
      {
        question: "Can the seller refuse to lower the price after a low appraisal?",
        answer:
          "Absolutely — the appraisal binds the lender's loan sizing, not the seller's price. If the seller holds firm and you cannot or will not cover the gap, the outcome is dictated by your contract's financing and appraisal terms: either you have a valid exit that preserves your deposit, or you are facing default. This is why those clauses and their deadlines matter before the appraisal, not after."
      },
      {
        question: "How long does an appraisal take in Florida?",
        answer:
          "From order to delivered report is commonly one to two weeks, but it stretches in busy season, in areas with few active appraisers, and after major storms when demand for property professionals spikes. Your loan officer sees the ordering pipeline, so ask early rather than assuming — the appraisal is a common critical-path item in Florida closing timelines."
      }
    ],
    sources: [
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "What is an appraisal?",
        url: "https://www.consumerfinance.gov/ask-cfpb/what-is-an-appraisal-en-167/"
      },
      {
        publisher: "Fannie Mae",
        title: "Appraiser requirements and expectations",
        url: "https://singlefamily.fanniemae.com/originating-underwriting/appraisers"
      }
    ],
    related: [
      { href: "/resources/closing-timeline-florida", label: "Florida closing timeline" },
      { href: "/resources/earnest-money-florida", label: "Earnest money in Florida" },
      { href: "/calculators/mortgage-payment", label: "Mortgage payment calculator" },
      { href: "/mortgage/conventional", label: "Conventional loans" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "underwriting-conditions",
    category: "first-time",
    title: "Underwriting Conditions: What They Are, How to Clear Them",
    description:
      "A conditional approval isn't a rejection — it's a checklist. What underwriting conditions are, why they exist, and how to clear them without delaying closing.",
    h1: "Underwriting conditions: why the lender keeps asking for more, and how to clear the list fast",
    answerSummary:
      "Underwriting conditions are the specific items an underwriter requires before final loan approval — an updated pay stub, a letter explaining a deposit, proof of insurance. A conditional approval means the loan is approved provided each item checks out, which makes conditions a checklist, not a rejection. They exist because every loan fact must be verified with documents. Clearing them fast comes down to responding completely, the same day, without editorializing.",
    sections: [
      {
        heading: "What a conditional approval actually means",
        paragraphs: [
          "After your file goes to underwriting, the usual outcome is not a clean yes or no — it is approved with conditions. An underwriter has reviewed your application against the loan program's guidelines, often alongside an automated underwriting system such as Fannie Mae's Desktop Underwriter, and concluded the loan works if a specific list of items is verified. That list is the conditions.",
          "First-time buyers routinely misread this moment. A conditional approval is good news: the hard decision has been made in your favor, contingent on evidence. The conditions are not the underwriter inventing obstacles; they are the gap between what your file claims and what it proves. Every material fact in a mortgage file — income, assets, debts, employment, the property itself — must be supported by documentation, and a condition is simply the name for a fact whose support is not yet in the file."
        ]
      },
      {
        heading: "The kinds of conditions you will actually see",
        paragraphs: [
          "Conditions sort into a few recognizable families, and knowing them removes most of the anxiety:"
        ],
        bullets: [
          "Documentation refresh: an updated pay stub or bank statement, because the originals aged past their validity window while the deal progressed",
          "Sourcing: a paper trail for a large deposit, gift funds documentation, or proof that earnest money cleared your account",
          "Letters of explanation: a short signed note on a credit inquiry, an address discrepancy, an employment gap, or anything in the file that needs context",
          "Employment and income: a verbal verification of employment near closing, or additional documents for self-employed, commission, or bonus income",
          "Property conditions: the appraisal itself, required repairs noted in it, the condo association's answers, or a termite inspection where required",
          "Insurance: proof of a bound homeowners policy — and flood insurance if the home is in a special flood hazard area — which in Florida is frequently the slowest condition on the list",
          "Prior-to-funding items: final housekeeping the closing team verifies on the last day, like the updated title commitment and the verbal employment check"
        ]
      },
      {
        heading: "Why lenders insist: the logic behind the paperwork",
        paragraphs: [
          "Every condition traces to the same principle: stated facts are not verified facts. The underwriter is certifying that this loan meets the program's guidelines, and that certification must survive an audit — Fannie Mae, Freddie Mac, FHA, and VA all review loan files after purchase or insurance, and a loan built on unverified claims can be pushed back onto the lender. The document requests that feel bureaucratic to you are the lender proving, item by item, that the loan it is about to fund is the loan it says it is.",
          "This is also why conditions keep appearing even late in the process. Documents expire on defined schedules, so a closing that drifts triggers refresh requests. And answers create questions: the bank statement you sent to satisfy one condition may show a new deposit that spawns another. This cascade is normal. It is not a sign your loan is in trouble; it is a sign the file is being read carefully."
        ]
      },
      {
        heading: "How to clear conditions fast",
        paragraphs: [
          "The speed at which conditions clear is mostly determined by the borrower, and the technique is unglamorous. Respond the same day, every time — underwriting queues are first-in, first-out at most lenders, and a document sent Friday instead of Tuesday can cost a week, not three days. Send complete documents: every page of the bank statement including the intentionally blank ones, because a statement that says page one of six will be conditioned again if five pages arrive. Send exactly what was asked for, not a substitute you consider equivalent.",
          "Letters of explanation should be short, factual, signed, and free of editorializing — the underwriter needs the fact contextualized, not an essay. And above all, keep the file frozen: no new credit accounts, no financed furniture, no job changes, no large unexplained deposits or transfers between preapproval and funding. Lenders refresh credit and re-verify employment shortly before closing, so mid-process changes are found, and each one reopens analysis that was finished.",
          "A good loan team makes this nearly painless by anticipating conditions before the underwriter asks — collecting the gift paper trail at preapproval, ordering condo documents on day one, flagging the insurance timeline in week one. That is much of what a broker is for: TRACT arranges loans through wholesale lenders and manages the conditions traffic between you and the underwriter, so the checklist shrinks on schedule instead of growing at the deadline."
        ]
      }
    ],
    faqs: [
      {
        question: "Is a conditional approval likely to become a final approval?",
        answer:
          "Usually, yes — when borrowers respond promptly and their finances hold still, conditional approvals routinely convert to clear-to-close. The conversions that fail typically involve a material fact changing mid-process: a job loss, new debt, an appraisal problem, or a document contradicting what the application claimed. The conditions themselves are the path to closing, not a threat to it."
      },
      {
        question: "Why is the lender asking for documents I already sent?",
        answer:
          "Three common reasons: the document aged past its validity window and needs a current version; the version you sent was incomplete — missing pages are the classic culprit; or the document answered one question while raising another, such as a statement revealing a new deposit. Occasionally it is simple duplication between systems. Annoying, but never worth slow-rolling: send it again, completely, the same day."
      },
      {
        question: "What does clear to close mean?",
        answer:
          "It means underwriting has verified every condition and the loan has final approval — the closing can be scheduled and the Closing Disclosure timeline begins. A few prior-to-funding checks still happen on the back end, including a verbal employment verification and often a credit refresh, so the freeze on new debt and job changes lasts until the loan actually funds, not until the words clear to close."
      },
      {
        question: "Can buying furniture on credit before closing really break my loan?",
        answer:
          "It genuinely can. A financed furniture purchase adds a monthly payment to your debt-to-income ratio, and lenders commonly refresh credit before funding. If the new payment pushes your ratio past the program's limit, the approval that was built on the old numbers no longer stands. Wait until after the loan funds; the sofa will still exist."
      }
    ],
    sources: [
      {
        publisher: "Fannie Mae",
        title: "Desktop Underwriter and Desktop Originator",
        url: "https://singlefamily.fanniemae.com/applications-technology/desktop-underwriter-desktop-originator"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Buying a House: Get ready to close",
        url: "https://www.consumerfinance.gov/owning-a-home/process/close/"
      }
    ],
    related: [
      { href: "/resources/gift-funds-rules", label: "Gift funds rules" },
      { href: "/resources/closing-timeline-florida", label: "Florida closing timeline" },
      { href: "/calculators/debt-to-income", label: "Debt-to-income calculator" },
      { href: "/mortgage/self-employed", label: "Self-employed borrowers" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  },
  {
    slug: "first-home-mistakes",
    category: "first-time",
    title: "First-Time Florida Buyer Mistakes to Avoid",
    description:
      "The mistakes Florida first-time buyers actually make: skipping insurance quotes, budgeting from the seller's tax bill, financing furniture mid-process, and more.",
    h1: "The mistakes first-time Florida buyers actually make",
    answerSummary:
      "The expensive first-time buyer mistakes in Florida are predictable: waiting until the last week to shop homeowners and flood insurance, budgeting from the seller's tax bill even though assessments reset at sale, financing furniture or a car while the loan is in underwriting, spending every dollar on the down payment, and treating contract deadlines casually. Each one is avoidable with a week-one habit rather than a closing-week scramble.",
    sections: [
      {
        heading: "Mistake one: treating insurance as a formality",
        paragraphs: [
          "In most states, homeowners insurance is a phone call. In Florida, it is a contingency in everything but name. Buyers who wait until the lender demands proof of coverage discover, days before closing, that insurers balk at the roof's age, that a four-point inspection is required and reveals an issue, or that the premium is far larger than the payment estimate assumed. Worse, if a named storm enters the forecast during hurricane season, carriers suspend binding new policies until it passes — and a closing without bound coverage simply waits.",
          "The fix costs nothing: get real quotes during the inspection period, while you can still negotiate or walk. Quote the flood policy too, not just the wind and homeowners coverage — flood damage is excluded from standard homeowners policies, lenders require flood insurance in FEMA special flood hazard areas, and FloodSmart.gov, the National Flood Insurance Program's consumer site, explains coverage and lets you understand the flood risk before you are committed. A quote in week one is information; a quote in week five is a crisis."
        ]
      },
      {
        heading: "Mistake two: budgeting from the seller's tax bill",
        paragraphs: [
          "The listing shows the seller's property tax bill, and buyers quietly build their budget on it. In Florida this number is close to meaningless for you. A longtime owner's assessed value has typically been suppressed for years by the homestead exemption and the Save Our Homes cap, which limits annual assessment growth on homesteaded property. When the home sells, that accumulated cap benefit resets, and the property is reassessed — so your tax bill can be dramatically higher than the one on the listing, and the jump often lands in your second year, after escrow was set from the old figures.",
          "Budget instead from the property's market value and your county's rates, and remember the exemption only helps once you qualify for and file it as your primary residence. The Florida Department of Revenue's property tax exemption pages explain homestead, Save Our Homes, and portability — including how a Florida seller can transfer accumulated benefit to their next Florida home. Ten minutes with your county property appraiser's tax estimator prevents the most common payment shock in Florida homeownership."
        ]
      },
      {
        heading: "Mistake three: changing your financial picture mid-process",
        paragraphs: [
          "Your loan approval is a photograph of your finances, and underwriting expects the subject to hold still until funding. The classic self-inflicted wound is financing furniture for the new house while the loan is in underwriting — a new account, a hard inquiry, and a monthly payment, all of which surface when the lender refreshes credit before closing. A financed car is the same mistake at larger scale. Debt-to-income math that worked at approval can fail at funding, and the approval fails with it.",
          "The freeze also covers quieter moves: changing jobs (even for more money, structure matters — salaried to commission is a downgrade in underwriting terms), moving money between accounts without a paper trail, making large cash deposits, or co-signing anyone's loan. The rule is simple and temporary: between application and funding, be financially boring. Every purchase can wait thirty days; your closing cannot always survive the alternative."
        ]
      },
      {
        heading: "The rest of the list: cash, contingencies, and condo diligence",
        paragraphs: [
          "A few more mistakes recur constantly, each preventable with one deliberate habit:"
        ],
        bullets: [
          "Spending every dollar on the down payment: Florida homes generate irregular expenses — storm deductibles, roof work, insurance jumps, condo assessments — and a buyer with zero reserves is one repair from real trouble; size your emergency fund before sizing your down payment",
          "Skipping the inspection or waiving contingencies to win a bidding war without understanding what was surrendered — the inspection period is your broadest exit and it is short",
          "Treating contract dates as soft: in Florida, deadlines are how deposits get lost; calendar every one the day you sign",
          "Buying a condo without reading the association's budget, reserves, and recent meeting minutes — the building's finances are as much your purchase as the unit is",
          "Never filing for the homestead exemption after moving in, leaving recurring tax savings unclaimed year after year",
          "Shopping monthly payment instead of total cost — insurance, taxes, and association dues are where Florida budgets actually break, not principal and interest",
          "Taking only one loan offer: comparing Loan Estimates from more than one lender, or having a broker shop wholesale lenders on one file, is the rare hour of work with a durable payoff"
        ]
      },
      {
        heading: "The habit underneath all of it",
        paragraphs: [
          "Notice the pattern: none of these mistakes involve bad luck. They are all sequencing errors — doing in week five what belonged in week one, or doing during underwriting what belonged after funding. First-time buyers are told the process is overwhelming, but the Florida-specific failure modes are a short list, and every one is beaten by the same habit: front-load the information gathering. Quotes, tax estimates, association documents, and loan comparisons all cost less early than late.",
          "This is also what a good loan team is for. TRACT arranges financing for Florida buyers and has watched every mistake on this page happen in the wild; the job is to make sure the insurance conversation, the tax reality check, and the do-not-finance-a-sofa speech all happen at preapproval, when they are free — not at the closing table, when they are not."
        ]
      }
    ],
    faqs: [
      {
        question: "When should I file for the Florida homestead exemption?",
        answer:
          "After you close and occupy the home as your permanent residence, file with your county property appraiser by the statutory deadline — the application window runs ahead of the tax year, with a filing deadline early in the year, and many counties accept filings online. Check your county property appraiser or the Florida Department of Revenue for the current deadline and required documents. Once granted, it generally renews automatically while your status is unchanged."
      },
      {
        question: "Do I really need flood insurance if I'm not on the coast?",
        answer:
          "Possibly. Lenders require it in FEMA special flood hazard areas, and plenty of inland Florida sits in them — flooding follows drainage, not ocean views. Even outside required zones, flood damage is excluded from standard homeowners policies, and lower-risk zones often price coverage more cheaply. Check the property's flood zone early through FloodSmart.gov or the FEMA flood maps, and get a quote before your inspection period ends."
      },
      {
        question: "How much should I keep in reserve after closing?",
        answer:
          "There is no universal figure, but the Florida-honest answer is: enough to cover your insurance deductibles — hurricane deductibles are typically a percentage of your dwelling coverage, not a flat amount — plus several months of total housing cost. Some loan programs require documented reserves anyway. If hitting your down payment target empties that cushion, a smaller down payment with reserves is usually the sturdier structure."
      },
      {
        question: "Is it really that bad to change jobs during the loan process?",
        answer:
          "It is a variable, and underwriting dislikes variables. A move within the same field, salaried to salaried, is often manageable with documentation — tell your loan officer before accepting. A move to commission-based, contract, or self-employment income is a genuine problem, because those income types typically require a history before they count. If a change is coming, the sequencing conversation with your loan officer should happen first, not after."
      }
    ],
    sources: [
      {
        publisher: "FloodSmart / National Flood Insurance Program",
        title: "FloodSmart.gov — the National Flood Insurance Program",
        url: "https://www.floodsmart.gov/"
      },
      {
        publisher: "Florida Department of Revenue",
        title: "Property tax exemptions and additional benefits",
        url: "https://floridarevenue.com/property/Pages/Taxpayers_Exemptions.aspx"
      },
      {
        publisher: "Florida Department of Financial Services",
        title: "Consumer insurance resources",
        url: "https://www.myfloridacfo.com/division/consumers/"
      },
      {
        publisher: "Consumer Financial Protection Bureau",
        title: "Buying a House: Get ready to close",
        url: "https://www.consumerfinance.gov/owning-a-home/process/close/"
      }
    ],
    related: [
      { href: "/resources/underwriting-conditions", label: "Underwriting conditions explained" },
      { href: "/resources/down-payment-how-much", label: "How much down payment do you need?" },
      { href: "/calculators/affordability", label: "Affordability calculator" },
      { href: "/locations/florida", label: "Florida mortgage services" },
      { href: "/plan", label: "Build your buying plan" }
    ],
    publishedAt: "2026-08-18",
    lastReviewed: "2026-08-18"
  }
];
