-- Exact-retry receipts and bounded first-party mortgage planning snapshots.
--
-- The submission UUID is generated by the browser and remains stable across an
-- ambiguous network retry. The advisory lock serializes only that submission;
-- the mapping returns the original lead without creating a second consent,
-- attribution, plan, or outbox row.

create table public.lead_submission_receipts (
  submission_id uuid primary key,
  lead_id uuid not null unique references public.leads(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.lead_plans (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null unique references public.leads(id) on delete restrict,
  submission_id uuid not null unique,
  source text not null check (
    source in (
      'mortgage_planner','mortgage_payment','affordability',
      'refinance_break_even','rent_vs_buy','closing_cost'
    )
  ),
  version text not null,
  calculation_version text not null,
  input_snapshot jsonb not null check (jsonb_typeof(input_snapshot) = 'object'),
  result_snapshot jsonb not null check (jsonb_typeof(result_snapshot) = 'object'),
  summary text not null,
  created_at timestamptz not null default now()
);

alter table public.lead_submission_receipts enable row level security;
alter table public.lead_plans enable row level security;

revoke all on public.lead_submission_receipts from anon;
revoke all on public.lead_plans from anon;

create policy "operations read submission receipts"
  on public.lead_submission_receipts for select to authenticated
  using (public.has_role('operations') or public.has_role('admin'));

create policy "assigned staff read lead plans"
  on public.lead_plans for select to authenticated
  using (
    public.has_role('operations')
    or public.has_role('admin')
    or exists (
      select 1
      from public.leads
      where leads.id = lead_plans.lead_id
        and leads.assigned_user_id = auth.uid()
    )
  );

drop function public.create_lead_with_receipt(jsonb, jsonb, jsonb, jsonb, uuid);

create function public.create_lead_with_receipt(
  p_lead jsonb,
  p_consent jsonb,
  p_attribution jsonb,
  p_outbox jsonb,
  p_request_id uuid,
  p_plan jsonb default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lead_id uuid;
  v_touch jsonb;
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_request_id::text, 0)
  );

  select lead_id
    into v_lead_id
    from public.lead_submission_receipts
   where submission_id = p_request_id;

  if v_lead_id is not null then
    return v_lead_id;
  end if;

  insert into public.leads (
    intent, first_name, last_name, email_normalized, phone_e164,
    preferred_contact, state_code, timeline, estimated_credit_band,
    message, source_path, dedupe_hash, status
  ) values (
    p_lead->>'intent',
    p_lead->>'first_name',
    p_lead->>'last_name',
    p_lead->>'email_normalized',
    p_lead->>'phone_e164',
    p_lead->>'preferred_contact',
    coalesce(p_lead->>'state_code', 'FL'),
    p_lead->>'timeline',
    p_lead->>'estimated_credit_band',
    p_lead->>'message',
    p_lead->>'source_path',
    p_lead->>'dedupe_hash',
    'queued'
  )
  returning id into v_lead_id;

  insert into public.consent_receipts (
    lead_id, privacy_accepted, contact_requested, sms_marketing, email_marketing,
    disclosure_version, disclosure_text_sha256, source_path, form_version,
    request_id, ip_prefix_hash, user_agent_family
  ) values (
    v_lead_id,
    (p_consent->>'privacy_accepted')::boolean,
    (p_consent->>'contact_requested')::boolean,
    coalesce((p_consent->>'sms_marketing')::boolean, false),
    coalesce((p_consent->>'email_marketing')::boolean, false),
    p_consent->>'disclosure_version',
    p_consent->>'disclosure_text_sha256',
    p_consent->>'source_path',
    p_consent->>'form_version',
    p_request_id,
    p_consent->>'ip_prefix_hash',
    p_consent->>'user_agent_family'
  );

  for v_touch in
    select value
      from pg_catalog.jsonb_array_elements(
        case
          when pg_catalog.jsonb_typeof(p_attribution) = 'array' then p_attribution
          else pg_catalog.jsonb_build_array(p_attribution)
        end
      )
  loop
    insert into public.attribution_touches (
      lead_id, touch_kind, occurred_at, landing_path, referrer_host,
      utm_source, utm_medium, utm_campaign, utm_content, utm_term,
      gclid, gbraid, wbraid, msclkid, fbclid
    ) values (
      v_lead_id,
      coalesce(v_touch->>'touch_kind', 'conversion'),
      coalesce((v_touch->>'occurred_at')::timestamptz, now()),
      v_touch->>'landing_path',
      v_touch->>'referrer_host',
      v_touch->>'utm_source',
      v_touch->>'utm_medium',
      v_touch->>'utm_campaign',
      v_touch->>'utm_content',
      v_touch->>'utm_term',
      v_touch->>'gclid',
      v_touch->>'gbraid',
      v_touch->>'wbraid',
      v_touch->>'msclkid',
      v_touch->>'fbclid'
    );
  end loop;

  insert into public.integration_outbox (
    aggregate_type, aggregate_id, event_type, idempotency_key, payload
  ) values (
    'lead', v_lead_id, p_outbox->>'event_type', p_outbox->>'idempotency_key', p_outbox->'payload'
  );

  if p_plan is not null then
    insert into public.lead_plans (
      lead_id, submission_id, source, version, calculation_version,
      input_snapshot, result_snapshot, summary
    ) values (
      v_lead_id,
      p_request_id,
      p_plan->>'source',
      p_plan->>'version',
      p_plan->>'calculation_version',
      p_plan->'input_snapshot',
      p_plan->'result_snapshot',
      p_plan->>'summary'
    );
  end if;

  insert into public.lead_submission_receipts (submission_id, lead_id)
  values (p_request_id, v_lead_id);

  return v_lead_id;
end;
$$;

revoke execute on function public.create_lead_with_receipt(jsonb, jsonb, jsonb, jsonb, uuid, jsonb) from public;
grant execute on function public.create_lead_with_receipt(jsonb, jsonb, jsonb, jsonb, uuid, jsonb) to service_role;
